##########################################################################
#
# Copyright 2011 Jose Fonseca
# All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
##########################################################################/


'''Describe GL parameters.'''


from .stdapi import *

from .gltypes import *


# Shorthands for the types
X = None # To be determined, merely an enum
B = GLboolean
I = GLint
I64 = GLint64
E = GLenum
F = GLfloat
D = GLdouble
P = OpaquePointer(Void)
S = CString
H = GLhandleARB

# A underscore prefix (e.g., _glGet) is used to skip automatic code generation
# for parameters that are obtained through other ways.

parameters = [
    # (functions, type, count, name) # value
    ("",	X,	1,	"GL_ZERO"),	# 0x0000
    ("",	X,	1,	"GL_ONE"),	# 0x0001

    # These are enumerated separately in GLenum_mode
    #("",	X,	1,	"GL_POINTS"),	# 0x0000
    #("",	X,	1,	"GL_LINES"),	# 0x0001
    #("",	X,	1,	"GL_LINE_LOOP"),	# 0x0002
    #("",	X,	1,	"GL_LINE_STRIP"),	# 0x0003
    #("",	X,	1,	"GL_TRIANGLES"),	# 0x0004
    #("",	X,	1,	"GL_TRIANGLE_STRIP"),	# 0x0005
    #("",	X,	1,	"GL_TRIANGLE_FAN"),	# 0x0006

    ("",	X,	1,	"GL_ADD"),	# 0x0104
    ("",	X,	1,	"GL_NEVER"),	# 0x0200
    ("",	X,	1,	"GL_LESS"),	# 0x0201
    ("",	X,	1,	"GL_EQUAL"),	# 0x0202
    ("",	X,	1,	"GL_LEQUAL"),	# 0x0203
    ("",	X,	1,	"GL_GREATER"),	# 0x0204
    ("",	X,	1,	"GL_NOTEQUAL"),	# 0x0205
    ("",	X,	1,	"GL_GEQUAL"),	# 0x0206
    ("",	X,	1,	"GL_ALWAYS"),	# 0x0207
    ("",	X,	1,	"GL_SRC_COLOR"),	# 0x0300
    ("",	X,	1,	"GL_ONE_MINUS_SRC_COLOR"),	# 0x0301
    ("",	X,	1,	"GL_SRC_ALPHA"),	# 0x0302
    ("",	X,	1,	"GL_ONE_MINUS_SRC_ALPHA"),	# 0x0303
    ("",	X,	1,	"GL_DST_ALPHA"),	# 0x0304
    ("",	X,	1,	"GL_ONE_MINUS_DST_ALPHA"),	# 0x0305
    ("",	X,	1,	"GL_DST_COLOR"),	# 0x0306
    ("",	X,	1,	"GL_ONE_MINUS_DST_COLOR"),	# 0x0307
    ("",	X,	1,	"GL_SRC_ALPHA_SATURATE"),	# 0x0308
    ("",	X,	1,	"GL_FRONT"),	# 0x0404
    ("",	X,	1,	"GL_BACK"),	# 0x0405
    ("",	X,	1,	"GL_FRONT_AND_BACK"),	# 0x0408
    ("",	X,	1,	"GL_INVALID_ENUM"),	# 0x0500
    ("",	X,	1,	"GL_INVALID_VALUE"),	# 0x0501
    ("",	X,	1,	"GL_INVALID_OPERATION"),	# 0x0502
    ("",	X,	1,	"GL_STACK_OVERFLOW"),	# 0x0503
    ("",	X,	1,	"GL_STACK_UNDERFLOW"),	# 0x0504
    ("",	X,	1,	"GL_OUT_OF_MEMORY"),	# 0x0505
    ("",	X,	1,	"GL_INVALID_FRAMEBUFFER_OPERATION"),	# 0x0506
    ("",	X,	1,	"GL_EXP"),	# 0x0800
    ("",	X,	1,	"GL_EXP2"),	# 0x0801
    ("",	X,	1,	"GL_CW"),	# 0x0900
    ("",	X,	1,	"GL_CCW"),	# 0x0901
    ("glGet",	F,	4,	"GL_CURRENT_COLOR"),	# 0x0B00
    ("glGet",	F,	3,	"GL_CURRENT_NORMAL"),	# 0x0B02
    ("glGet",	F,	4,	"GL_CURRENT_TEXTURE_COORDS"),	# 0x0B03
    ("glGet",	B,	1,	"GL_POINT_SMOOTH"),	# 0x0B10
    ("glGet",	F,	1,	"GL_POINT_SIZE"),	# 0x0B11
    ("glGet",	B,	1,	"GL_LINE_SMOOTH"),	# 0x0B20
    ("glGet",	F,	1,	"GL_LINE_WIDTH"),	# 0x0B21
    ("glGet",	B,	1,	"GL_CULL_FACE"),	# 0x0B44
    ("glGet",	E,	1,	"GL_CULL_FACE_MODE"),	# 0x0B45
    ("glGet",	E,	1,	"GL_FRONT_FACE"),	# 0x0B46
    ("glGet",	B,	1,	"GL_LIGHTING"),	# 0x0B50
    ("glGet",	B,	1,	"GL_LIGHT_MODEL_TWO_SIDE"),	# 0x0B52
    ("glGet",	F,	4,	"GL_LIGHT_MODEL_AMBIENT"),	# 0x0B53
    ("glGet",	E,	1,	"GL_SHADE_MODEL"),	# 0x0B54
    ("glGet",	B,	1,	"GL_COLOR_MATERIAL"),	# 0x0B57
    ("glGet",	B,	1,	"GL_FOG"),	# 0x0B60
    ("glGet",	F,	1,	"GL_FOG_DENSITY"),	# 0x0B62
    ("glGet",	F,	1,	"GL_FOG_START"),	# 0x0B63
    ("glGet",	F,	1,	"GL_FOG_END"),	# 0x0B64
    ("glGet",	E,	1,	"GL_FOG_MODE"),	# 0x0B65
    ("glGet",	F,	4,	"GL_FOG_COLOR"),	# 0x0B66
    ("glGet",	F,	2,	"GL_DEPTH_RANGE"),	# 0x0B70
    ("glGet",	B,	1,	"GL_DEPTH_TEST"),	# 0x0B71
    ("glGet",	B,	1,	"GL_DEPTH_WRITEMASK"),	# 0x0B72
    ("glGet",	F,	1,	"GL_DEPTH_CLEAR_VALUE"),	# 0x0B73
    ("glGet",	E,	1,	"GL_DEPTH_FUNC"),	# 0x0B74
    ("glGet",	B,	1,	"GL_STENCIL_TEST"),	# 0x0B90
    ("glGet",	I,	1,	"GL_STENCIL_CLEAR_VALUE"),	# 0x0B91
    ("glGet",	E,	1,	"GL_STENCIL_FUNC"),	# 0x0B92
    ("glGet",	I,	1,	"GL_STENCIL_VALUE_MASK"),	# 0x0B93
    ("glGet",	E,	1,	"GL_STENCIL_FAIL"),	# 0x0B94
    ("glGet",	E,	1,	"GL_STENCIL_PASS_DEPTH_FAIL"),	# 0x0B95
    ("glGet",	E,	1,	"GL_STENCIL_PASS_DEPTH_PASS"),	# 0x0B96
    ("glGet",	I,	1,	"GL_STENCIL_REF"),	# 0x0B97
    ("glGet",	I,	1,	"GL_STENCIL_WRITEMASK"),	# 0x0B98
    ("glGet",	E,	1,	"GL_MATRIX_MODE"),	# 0x0BA0
    ("glGet",	B,	1,	"GL_NORMALIZE"),	# 0x0BA1
    ("glGet",	I,	4,	"GL_VIEWPORT"),	# 0x0BA2
    ("glGet",	I,	1,	"GL_MODELVIEW_STACK_DEPTH"),	# 0x0BA3
    ("glGet",	I,	1,	"GL_PROJECTION_STACK_DEPTH"),	# 0x0BA4
    ("glGet",	I,	1,	"GL_TEXTURE_STACK_DEPTH"),	# 0x0BA5
    ("glGet",	F,	16,	"GL_MODELVIEW_MATRIX"),	# 0x0BA6
    ("glGet",	F,	16,	"GL_PROJECTION_MATRIX"),	# 0x0BA7
    ("glGet",	F,	16,	"GL_TEXTURE_MATRIX"),	# 0x0BA8
    ("glGet",	B,	1,	"GL_ALPHA_TEST"),	# 0x0BC0
    ("glGet",	E,	1,	"GL_ALPHA_TEST_FUNC"),	# 0x0BC1
    ("glGet",	F,	1,	"GL_ALPHA_TEST_REF"),	# 0x0BC2
    ("glGet",	B,	1,	"GL_DITHER"),	# 0x0BD0
    ("glGet",	E,	1,	"GL_BLEND_DST"),	# 0x0BE0
    ("glGet",	E,	1,	"GL_BLEND_SRC"),	# 0x0BE1
    ("glGet",	B,	1,	"GL_BLEND"),	# 0x0BE2
    ("glGet",	E,	1,	"GL_LOGIC_OP_MODE"),	# 0x0BF0
    ("glGet",	B,	1,	"GL_COLOR_LOGIC_OP"),	# 0x0BF2
    ("glGet",	E,	1,	"GL_READ_BUFFER"),	# 0x0C02
    ("glGet",	I,	4,	"GL_SCISSOR_BOX"),	# 0x0C10
    ("glGet",	B,	1,	"GL_SCISSOR_TEST"),	# 0x0C11
    ("glGet",	F,	4,	"GL_COLOR_CLEAR_VALUE"),	# 0x0C22
    ("glGet",	B,	4,	"GL_COLOR_WRITEMASK"),	# 0x0C23
    ("glGet",	E,	1,	"GL_PERSPECTIVE_CORRECTION_HINT"),	# 0x0C50
    ("glGet",	E,	1,	"GL_POINT_SMOOTH_HINT"),	# 0x0C51
    ("glGet",	E,	1,	"GL_LINE_SMOOTH_HINT"),	# 0x0C52
    ("glGet",	E,	1,	"GL_FOG_HINT"),	# 0x0C54
    ("glGet",	I,	1,	"GL_UNPACK_ROW_LENGTH"),	# 0x0CF2
    ("glGet",	I,	1,	"GL_UNPACK_SKIP_ROWS"),	# 0x0CF3
    ("glGet",	I,	1,	"GL_UNPACK_SKIP_PIXELS"),	# 0x0CF4
    ("glGet",	I,	1,	"GL_UNPACK_ALIGNMENT"),	# 0x0CF5
    ("glGet",	I,	1,	"GL_PACK_ROW_LENGTH"),	# 0x0D02
    ("glGet",	I,	1,	"GL_PACK_SKIP_ROWS"),	# 0x0D03
    ("glGet",	I,	1,	"GL_PACK_SKIP_PIXELS"),	# 0x0D04
    ("glGet",	I,	1,	"GL_PACK_ALIGNMENT"),	# 0x0D05
    ("glGet,glGetTexEnv",	F,	1,	"GL_ALPHA_SCALE"),	# 0x0D1C
    ("glGet",	I,	1,	"GL_MAX_LIGHTS"),	# 0x0D31
    ("glGet",	I,	1,	"GL_MAX_TEXTURE_SIZE"),	# 0x0D33
    ("glGet",	I,	1,	"GL_MAX_MODELVIEW_STACK_DEPTH"),	# 0x0D36
    ("glGet",	I,	1,	"GL_MAX_PROJECTION_STACK_DEPTH"),	# 0x0D38
    ("glGet",	I,	1,	"GL_MAX_TEXTURE_STACK_DEPTH"),	# 0x0D39
    ("glGet",	F,	2,	"GL_MAX_VIEWPORT_DIMS"),	# 0x0D3A
    ("glGet",	I,	1,	"GL_SUBPIXEL_BITS"),	# 0x0D50
    ("glGet",	I,	1,	"GL_RED_BITS"),	# 0x0D52
    ("glGet",	I,	1,	"GL_GREEN_BITS"),	# 0x0D53
    ("glGet",	I,	1,	"GL_BLUE_BITS"),	# 0x0D54
    ("glGet",	I,	1,	"GL_ALPHA_BITS"),	# 0x0D55
    ("glGet",	I,	1,	"GL_DEPTH_BITS"),	# 0x0D56
    ("glGet",	I,	1,	"GL_STENCIL_BITS"),	# 0x0D57
    ("_glGet",	B,	1,	"GL_TEXTURE_2D"),	# 0x0DE1
    ("glGetTexParameter,glGetSamplerParameter",	F,	4,	"GL_TEXTURE_BORDER_COLOR_EXT"),	# 0x1004
    ("glGetTexLevelParameter",	I,	1,	"GL_TEXTURE_BORDER"),	# 0x1005
    ("",	X,	1,	"GL_DONT_CARE"),	# 0x1100
    ("",	X,	1,	"GL_FASTEST"),	# 0x1101
    ("",	X,	1,	"GL_NICEST"),	# 0x1102
    ("glGetLight,glGetMaterial",	F,	4,	"GL_AMBIENT"),	# 0x1200
    ("glGetLight,glGetMaterial",	F,	4,	"GL_DIFFUSE"),	# 0x1201
    ("glGetLight,glGetMaterial",	F,	4,	"GL_SPECULAR"),	# 0x1202
    ("glGetLight",	F,	4,	"GL_POSITION"),	# 0x1203
    ("glGetLight",	F,	3,	"GL_SPOT_DIRECTION"),	# 0x1204
    ("glGetLight",	F,	1,	"GL_SPOT_EXPONENT"),	# 0x1205
    ("glGetLight",	F,	1,	"GL_SPOT_CUTOFF"),	# 0x1206
    ("glGetLight",	F,	1,	"GL_CONSTANT_ATTENUATION"),	# 0x1207
    ("glGetLight",	F,	1,	"GL_LINEAR_ATTENUATION"),	# 0x1208
    ("glGetLight",	F,	1,	"GL_QUADRATIC_ATTENUATION"),	# 0x1209
    ("",	X,	1,	"GL_BYTE"),	# 0x1400
    ("",	X,	1,	"GL_UNSIGNED_BYTE"),	# 0x1401
    ("",	X,	1,	"GL_SHORT"),	# 0x1402
    ("",	X,	1,	"GL_UNSIGNED_SHORT"),	# 0x1403
    ("",	X,	1,	"GL_INT"),	# 0x1404
    ("",	X,	1,	"GL_UNSIGNED_INT"),	# 0x1405
    ("",	X,	1,	"GL_FLOAT"),	# 0x1406
    ("",	X,	1,	"GL_HALF_FLOAT"),	# 0x140B
    ("",	X,	1,	"GL_FIXED"),	# 0x140C
    ("",	X,	1,	"GL_CLEAR"),	# 0x1500
    ("",	X,	1,	"GL_AND"),	# 0x1501
    ("",	X,	1,	"GL_AND_REVERSE"),	# 0x1502
    ("",	X,	1,	"GL_COPY"),	# 0x1503
    ("",	X,	1,	"GL_AND_INVERTED"),	# 0x1504
    ("",	X,	1,	"GL_NOOP"),	# 0x1505
    ("",	X,	1,	"GL_XOR"),	# 0x1506
    ("",	X,	1,	"GL_OR"),	# 0x1507
    ("",	X,	1,	"GL_NOR"),	# 0x1508
    ("",	X,	1,	"GL_EQUIV"),	# 0x1509
    ("",	X,	1,	"GL_INVERT"),	# 0x150A
    ("",	X,	1,	"GL_OR_REVERSE"),	# 0x150B
    ("",	X,	1,	"GL_COPY_INVERTED"),	# 0x150C
    ("",	X,	1,	"GL_OR_INVERTED"),	# 0x150D
    ("",	X,	1,	"GL_NAND"),	# 0x150E
    ("",	X,	1,	"GL_SET"),	# 0x150F
    ("glGetMaterial",	F,	4,	"GL_EMISSION"),	# 0x1600
    ("glGetMaterial",	F,	1,	"GL_SHININESS"),	# 0x1601
    ("",	F,	4,	"GL_AMBIENT_AND_DIFFUSE"),	# 0x1602
    ("",	X,	1,	"GL_MODELVIEW"),	# 0x1700
    ("",	X,	1,	"GL_PROJECTION"),	# 0x1701
    ("",	X,	1,	"GL_TEXTURE"),	# 0x1702
    ("glClearBuffer",	F,	1,	"GL_COLOR"),	# 0x1800 (a 32bit value)
    ("glClearBuffer",	F,	1,	"GL_DEPTH"),	# 0x1801 (a 32bit value)
    ("",	X,	1,	"GL_STENCIL"),	# 0x1802
    ("",	X,	1,	"GL_DEPTH_COMPONENT"),	# 0x1902
    ("",	X,	1,	"GL_RED"),	# 0x1903
    ("",	X,	1,	"GL_GREEN"),	# 0x1904
    ("",	X,	1,	"GL_BLUE"),	# 0x1905
    ("",	X,	1,	"GL_ALPHA"),	# 0x1906
    ("",	X,	1,	"GL_RGB"),	# 0x1907
    ("",	X,	1,	"GL_RGBA"),	# 0x1908
    ("",	X,	1,	"GL_LUMINANCE"),	# 0x1909
    ("",	X,	1,	"GL_LUMINANCE_ALPHA"),	# 0x190A
    ("",	X,	1,	"GL_FLAT"),	# 0x1D00
    ("",	X,	1,	"GL_SMOOTH"),	# 0x1D01
    ("",	X,	1,	"GL_KEEP"),	# 0x1E00
    ("",	X,	1,	"GL_REPLACE"),	# 0x1E01
    ("",	X,	1,	"GL_INCR"),	# 0x1E02
    ("",	X,	1,	"GL_DECR"),	# 0x1E03
    ("glGet",	S,	1,	"GL_VENDOR"),	# 0x1F00
    ("glGet",	S,	1,	"GL_RENDERER"),	# 0x1F01
    ("glGet",	S,	1,	"GL_VERSION"),	# 0x1F02
    ("glGet",	S,	1,	"GL_EXTENSIONS"),	# 0x1F03
    ("",	X,	1,	"GL_MODULATE"),	# 0x2100
    ("",	X,	1,	"GL_DECAL"),	# 0x2101
    ("glGetTexEnv",	E,	1,	"GL_TEXTURE_ENV_MODE"),	# 0x2200
    ("glGetTexEnv",	F,	4,	"GL_TEXTURE_ENV_COLOR"),	# 0x2201
    ("",	X,	1,	"GL_TEXTURE_ENV"),	# 0x2300
    ("",	X,	1,	"GL_NEAREST"),	# 0x2600
    ("",	X,	1,	"GL_LINEAR"),	# 0x2601
    ("",	X,	1,	"GL_NEAREST_MIPMAP_NEAREST"),	# 0x2700
    ("",	X,	1,	"GL_LINEAR_MIPMAP_NEAREST"),	# 0x2701
    ("",	X,	1,	"GL_NEAREST_MIPMAP_LINEAR"),	# 0x2702
    ("",	X,	1,	"GL_LINEAR_MIPMAP_LINEAR"),	# 0x2703
    ("glGetTexParameter",	E,	1,	"GL_TEXTURE_MAG_FILTER"),	# 0x2800
    ("glGetTexParameter",	E,	1,	"GL_TEXTURE_MIN_FILTER"),	# 0x2801
    ("glGetTexParameter",	E,	1,	"GL_TEXTURE_WRAP_S"),	# 0x2802
    ("glGetTexParameter",	E,	1,	"GL_TEXTURE_WRAP_T"),	# 0x2803
    ("",	X,	1,	"GL_REPEAT"),	# 0x2901
    ("glGet",	F,	1,	"GL_POLYGON_OFFSET_UNITS"),	# 0x2A00
    ("_glGet",	B,	1,	"GL_LIGHT0"),	# 0x4000
    ("_glGet",	B,	1,	"GL_LIGHT1"),	# 0x4001
    ("_glGet",	B,	1,	"GL_LIGHT2"),	# 0x4002
    ("_glGet",	B,	1,	"GL_LIGHT3"),	# 0x4003
    ("_glGet",	B,	1,	"GL_LIGHT4"),	# 0x4004
    ("_glGet",	B,	1,	"GL_LIGHT5"),	# 0x4005
    ("_glGet",	B,	1,	"GL_LIGHT6"),	# 0x4006
    ("_glGet",	B,	1,	"GL_LIGHT7"),	# 0x4007
    ("",	X,	1,	"GL_CONSTANT_COLOR"),	# 0x8001
    ("",	X,	1,	"GL_ONE_MINUS_CONSTANT_COLOR"),	# 0x8002
    ("",	X,	1,	"GL_CONSTANT_ALPHA"),	# 0x8003
    ("",	X,	1,	"GL_ONE_MINUS_CONSTANT_ALPHA"),	# 0x8004
    ("glGet",	F,	4,	"GL_BLEND_COLOR"),	# 0x8005
    ("",	X,	1,	"GL_FUNC_ADD"),	# 0x8006
    ("",	X,	1,	"GL_MIN"),	# 0x8007
    ("",	X,	1,	"GL_MAX"),	# 0x8008
    ("glGet",	E,	1,	"GL_BLEND_EQUATION_RGB"),	# 0x8009
    ("",	X,	1,	"GL_FUNC_SUBTRACT"),	# 0x800A
    ("",	X,	1,	"GL_FUNC_REVERSE_SUBTRACT"),	# 0x800B
    ("",	X,	1,	"GL_UNSIGNED_SHORT_4_4_4_4"),	# 0x8033
    ("",	X,	1,	"GL_UNSIGNED_SHORT_5_5_5_1"),	# 0x8034
    ("glGet",	B,	1,	"GL_POLYGON_OFFSET_FILL"),	# 0x8037
    ("glGet",	F,	1,	"GL_POLYGON_OFFSET_FACTOR"),	# 0x8038
    ("glGet",	B,	1,	"GL_RESCALE_NORMAL"),	# 0x803A
    ("",	X,	1,	"GL_RGB8"),	# 0x8051
    ("",	X,	1,	"GL_RGBA4"),	# 0x8056
    ("",	X,	1,	"GL_RGB5_A1"),	# 0x8057
    ("",	X,	1,	"GL_RGBA8"),	# 0x8058
    ("",	X,	1,	"GL_RGB10_A2"),	# 0x8059
    ("_glGet",	I,	1,	"GL_TEXTURE_BINDING_2D"),	# 0x8069
    ("_glGet",	I,	1,	"GL_TEXTURE_BINDING_3D"),	# 0x806A
    ("glGet",	I,	1,	"GL_UNPACK_SKIP_IMAGES"),	# 0x806D
    ("glGet",	F,	1,	"GL_UNPACK_IMAGE_HEIGHT"),	# 0x806E
    ("glGet",	B,	1,	"GL_TEXTURE_3D"),	# 0x806F
    ("glGetTexParameter",	E,	1,	"GL_TEXTURE_WRAP_R"),	# 0x8072
    ("glGet",	I,	1,	"GL_MAX_3D_TEXTURE_SIZE"),	# 0x8073
    ("glGet",	B,	1,	"GL_VERTEX_ARRAY"),	# 0x8074
    ("glGet",	B,	1,	"GL_NORMAL_ARRAY"),	# 0x8075
    ("glGet",	B,	1,	"GL_COLOR_ARRAY"),	# 0x8076
    ("glGet",	B,	1,	"GL_TEXTURE_COORD_ARRAY"),	# 0x8078
    ("glGet",	I,	1,	"GL_VERTEX_ARRAY_SIZE"),	# 0x807A
    ("glGet",	E,	1,	"GL_VERTEX_ARRAY_TYPE"),	# 0x807B
    ("glGet",	I,	1,	"GL_VERTEX_ARRAY_STRIDE"),	# 0x807C
    ("glGet",	E,	1,	"GL_NORMAL_ARRAY_TYPE"),	# 0x807E
    ("glGet",	I,	1,	"GL_NORMAL_ARRAY_STRIDE"),	# 0x807F
    ("glGet",	I,	1,	"GL_COLOR_ARRAY_SIZE"),	# 0x8081
    ("glGet",	E,	1,	"GL_COLOR_ARRAY_TYPE"),	# 0x8082
    ("glGet",	I,	1,	"GL_COLOR_ARRAY_STRIDE"),	# 0x8083
    ("glGet",	I,	1,	"GL_TEXTURE_COORD_ARRAY_SIZE"),	# 0x8088
    ("glGet",	E,	1,	"GL_TEXTURE_COORD_ARRAY_TYPE"),	# 0x8089
    ("glGet",	I,	1,	"GL_TEXTURE_COORD_ARRAY_STRIDE"),	# 0x808A
    ("glGet",	P,	1,	"GL_VERTEX_ARRAY_POINTER"),	# 0x808E
    ("glGet",	P,	1,	"GL_NORMAL_ARRAY_POINTER"),	# 0x808F
    ("glGet",	P,	1,	"GL_COLOR_ARRAY_POINTER"),	# 0x8090
    ("glGet",	P,	1,	"GL_TEXTURE_COORD_ARRAY_POINTER"),	# 0x8092
    ("glGet",	I,	1,	"GL_MULTISAMPLE"),	# 0x809D
    ("glGet",	I,	1,	"GL_SAMPLE_ALPHA_TO_COVERAGE"),	# 0x809E
    ("glGet",	I,	1,	"GL_SAMPLE_ALPHA_TO_ONE"),	# 0x809F
    ("glGet",	I,	1,	"GL_SAMPLE_COVERAGE"),	# 0x80A0
    ("glGet",	I,	1,	"GL_SAMPLE_BUFFERS"),	# 0x80A8
    ("glGet",	I,	1,	"GL_SAMPLES"),	# 0x80A9
    ("glGet",	F,	1,	"GL_SAMPLE_COVERAGE_VALUE"),	# 0x80AA
    ("glGet",	I,	1,	"GL_SAMPLE_COVERAGE_INVERT"),	# 0x80AB
    ("glGet",	E,	1,	"GL_BLEND_DST_RGB"),	# 0x80C8
    ("glGet",	E,	1,	"GL_BLEND_SRC_RGB"),	# 0x80C9
    ("glGet",	E,	1,	"GL_BLEND_DST_ALPHA"),	# 0x80CA
    ("glGet",	E,	1,	"GL_BLEND_SRC_ALPHA"),	# 0x80CB
    ("glGet",	I,	1,	"GL_MAX_ELEMENTS_VERTICES"),	# 0x80E8
    ("glGet",	I,	1,	"GL_MAX_ELEMENTS_INDICES"),	# 0x80E9
    ("glGet",	F,	1,	"GL_POINT_SIZE_MIN"),	# 0x8126
    ("glGet",	F,	1,	"GL_POINT_SIZE_MAX"),	# 0x8127
    ("glGet",	F,	1,	"GL_POINT_FADE_THRESHOLD_SIZE"),	# 0x8128
    ("glGet",	F,	3,	"GL_POINT_DISTANCE_ATTENUATION"),	# 0x8129
    ("glGet",	I,	1,	"GL_CLAMP_TO_BORDER_EXT"),	# 0x812D
    ("",	X,	1,	"GL_CLAMP_TO_EDGE"),	# 0x812F
    ("glGetTexParameter",	F,	1,	"GL_TEXTURE_MIN_LOD"),	# 0x813A
    ("glGetTexParameter",	F,	1,	"GL_TEXTURE_MAX_LOD"),	# 0x813B
    ("glGetTexParameter",	F,	1,	"GL_TEXTURE_BASE_LEVEL"),	# 0x813C
    ("glGetTexParameter",	F,	1,	"GL_TEXTURE_MAX_LEVEL"),	# 0x813D
    ("glGetTexParameter",	B,	1,	"GL_GENERATE_MIPMAP"),	# 0x8191
    ("glGet",	E,	1,	"GL_GENERATE_MIPMAP_HINT"),	# 0x8192
    ("",	X,	1,	"GL_DEPTH_COMPONENT16"),	# 0x81A5
    ("",	X,	1,	"GL_DEPTH_COMPONENT24"),	# 0x81A6
    ("glGetFramebufferAttachmentParameter",	E,	1,	"GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING"),	# 0x8210
    ("glGetFramebufferAttachmentParameter",	E,	1,	"GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE"),	# 0x8211
    ("glGetFramebufferAttachmentParameter",	I,	1,	"GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE"),	# 0x8212
    ("glGetFramebufferAttachmentParameter",	I,	1,	"GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE"),	# 0x8213
    ("glGetFramebufferAttachmentParameter",	I,	1,	"GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE"),	# 0x8214
    ("glGetFramebufferAttachmentParameter",	I,	1,	"GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE"),	# 0x8215
    ("glGetFramebufferAttachmentParameter",	I,	1,	"GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE"),	# 0x8216
    ("glGetFramebufferAttachmentParameter",	I,	1,	"GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE"),	# 0x8217
    ("",	X,	1,	"GL_FRAMEBUFFER_DEFAULT"),	# 0x8218
    ("",	X,	1,	"GL_FRAMEBUFFER_UNDEFINED"),	# 0x8219
    ("",	X,	1,	"GL_DEPTH_STENCIL_ATTACHMENT"),	# 0x821A
    ("glGet",	I,	1,	"GL_MAJOR_VERSION"),	# 0x821B
    ("glGet",	I,	1,	"GL_MINOR_VERSION"),	# 0x821C
    ("glGet",	I,	1,	"GL_NUM_EXTENSIONS"),	# 0x821D
    ("glGetBufferParameter",	B,	1,	"GL_BUFFER_IMMUTABLE_STORAGE"),	# 0x821F
    ("glGetBufferParameter",	I,	1,	"GL_BUFFER_STORAGE_FLAGS"),	# 0x8220
    ("glGet",	B,	1,	"GL_PRIMITIVE_RESTART_FOR_PATCHES_SUPPORTED"),	# 0x8221
    ("",	X,	1,	"GL_RG"),	# 0x8227
    ("",	X,	1,	"GL_RG_INTEGER"),	# 0x8228
    ("",	X,	1,	"GL_R8"),	# 0x8229
    ("",	X,	1,	"GL_RG8"),	# 0x822B
    ("",	X,	1,	"GL_R16F"),	# 0x822D
    ("",	X,	1,	"GL_R32F"),	# 0x822E
    ("",	X,	1,	"GL_RG16F"),	# 0x822F
    ("",	X,	1,	"GL_RG32F"),	# 0x8230
    ("",	X,	1,	"GL_R8I"),	# 0x8231
    ("",	X,	1,	"GL_R8UI"),	# 0x8232
    ("",	X,	1,	"GL_R16I"),	# 0x8233
    ("",	X,	1,	"GL_R16UI"),	# 0x8234
    ("",	X,	1,	"GL_R32I"),	# 0x8235
    ("",	X,	1,	"GL_R32UI"),	# 0x8236
    ("",	X,	1,	"GL_RG8I"),	# 0x8237
    ("",	X,	1,	"GL_RG8UI"),	# 0x8238
    ("",	X,	1,	"GL_RG16I"),	# 0x8239
    ("",	X,	1,	"GL_RG16UI"),	# 0x823A
    ("",	X,	1,	"GL_RG32I"),	# 0x823B
    ("",	X,	1,	"GL_RG32UI"),	# 0x823C
    ("glGet",	B,	1,	"GL_DEBUG_OUTPUT_SYNCHRONOUS"),	# 0x8242
    ("glGet",	I,	1,	"GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH"),	# 0x8243
    ("glGet",	P,	1,	"GL_DEBUG_CALLBACK_FUNCTION"),	# 0x8244
    ("glGet",	P,	1,	"GL_DEBUG_CALLBACK_USER_PARAM"),	# 0x8245
    ("glGet",	E,	1,	"GL_RESET_NOTIFICATION_STRATEGY_ARB"),  # 0x8256
    ("",	X,	1,	"GL_PROGRAM_BINARY_RETRIEVABLE_HINT"),	# 0x8257
    ("glGet",	E,	1,	"GL_LAYER_PROVOKING_VERTEX_EXT"),	# 0x825E
    ("glGet",	I,	1,	"GL_MAX_DEBUG_GROUP_STACK_DEPTH"),	# 0x826C
    ("glGet",	I,	1,	"GL_DEBUG_GROUP_STACK_DEPTH"),	# 0x826D
    ("",	X,	1,	"GL_UNSIGNED_SHORT_5_6_5"),	# 0x8363
    ("",	X,	1,	"GL_UNSIGNED_INT_2_10_10_10_REV"),	# 0x8368
    ("",	X,	1,	"GL_MIRRORED_REPEAT"),	# 0x8370
    ("",	X,	1,	"GL_COMPRESSED_RGB_S3TC_DXT1_EXT"),	# 0x83F0
    ("",	X,	1,	"GL_COMPRESSED_RGBA_S3TC_DXT1_EXT"),	# 0x83F1
    ("glGet",	F,	2,	"GL_ALIASED_POINT_SIZE_RANGE"),	# 0x846D
    ("glGet",	F,	2,	"GL_ALIASED_LINE_WIDTH_RANGE"),	# 0x846E
    ("",	X,	1,	"GL_TEXTURE0"),	# 0x84C0
    ("",	X,	1,	"GL_TEXTURE1"),	# 0x84C1
    ("",	X,	1,	"GL_TEXTURE2"),	# 0x84C2
    ("",	X,	1,	"GL_TEXTURE3"),	# 0x84C3
    ("",	X,	1,	"GL_TEXTURE4"),	# 0x84C4
    ("",	X,	1,	"GL_TEXTURE5"),	# 0x84C5
    ("",	X,	1,	"GL_TEXTURE6"),	# 0x84C6
    ("",	X,	1,	"GL_TEXTURE7"),	# 0x84C7
    ("",	X,	1,	"GL_TEXTURE8"),	# 0x84C8
    ("",	X,	1,	"GL_TEXTURE9"),	# 0x84C9
    ("",	X,	1,	"GL_TEXTURE10"),	# 0x84CA
    ("",	X,	1,	"GL_TEXTURE11"),	# 0x84CB
    ("",	X,	1,	"GL_TEXTURE12"),	# 0x84CC
    ("",	X,	1,	"GL_TEXTURE13"),	# 0x84CD
    ("",	X,	1,	"GL_TEXTURE14"),	# 0x84CE
    ("",	X,	1,	"GL_TEXTURE15"),	# 0x84CF
    ("",	X,	1,	"GL_TEXTURE16"),	# 0x84D0
    ("",	X,	1,	"GL_TEXTURE17"),	# 0x84D1
    ("",	X,	1,	"GL_TEXTURE18"),	# 0x84D2
    ("",	X,	1,	"GL_TEXTURE19"),	# 0x84D3
    ("",	X,	1,	"GL_TEXTURE20"),	# 0x84D4
    ("",	X,	1,	"GL_TEXTURE21"),	# 0x84D5
    ("",	X,	1,	"GL_TEXTURE22"),	# 0x84D6
    ("",	X,	1,	"GL_TEXTURE23"),	# 0x84D7
    ("",	X,	1,	"GL_TEXTURE24"),	# 0x84D8
    ("",	X,	1,	"GL_TEXTURE25"),	# 0x84D9
    ("",	X,	1,	"GL_TEXTURE26"),	# 0x84DA
    ("",	X,	1,	"GL_TEXTURE27"),	# 0x84DB
    ("",	X,	1,	"GL_TEXTURE28"),	# 0x84DC
    ("",	X,	1,	"GL_TEXTURE29"),	# 0x84DD
    ("",	X,	1,	"GL_TEXTURE30"),	# 0x84DE
    ("",	X,	1,	"GL_TEXTURE31"),	# 0x84DF
    ("glGet",	E,	1,	"GL_ACTIVE_TEXTURE"),	# 0x84E0
    ("glGet",	E,	1,	"GL_CLIENT_ACTIVE_TEXTURE"),	# 0x84E1
    ("glGet",	I,	1,	"GL_MAX_TEXTURE_UNITS"),	# 0x84E2
    ("",	X,	1,	"GL_SUBTRACT"),	# 0x84E7
    ("glGet",	I,	1,	"GL_MAX_RENDERBUFFER_SIZE"),	# 0x84E8
    ("",	X,	1,	"GL_ALL_COMPLETED_NV"),	# 0x84F2
    ("",	X,	1,	"GL_FENCE_STATUS_NV"),	# 0x84F3
    ("",	X,	1,	"GL_FENCE_CONDITION_NV"),	# 0x84F4
    ("",	X,	1,	"GL_DEPTH_STENCIL"),	# 0x84F9
    ("",	X,	1,	"GL_UNSIGNED_INT_24_8"),	# 0x84FA
    ("glGet",	F,	1,	"GL_MAX_TEXTURE_LOD_BIAS"),	# 0x84FD
    ("glGetTexParameter",	F,	1,	"GL_TEXTURE_MAX_ANISOTROPY_EXT"),	# 0x84FE
    ("glGet",	F,	1,	"GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT"),	# 0x84FF
    ("",	X,	1,	"GL_INCR_WRAP"),	# 0x8507
    ("",	X,	1,	"GL_DECR_WRAP"),	# 0x8508
    ("_glGet",	B,	1,	"GL_TEXTURE_CUBE_MAP"),	# 0x8513
    ("_glGet",	I,	1,	"GL_TEXTURE_BINDING_CUBE_MAP"),	# 0x8514
    ("",	X,	1,	"GL_TEXTURE_CUBE_MAP_POSITIVE_X"),	# 0x8515
    ("",	X,	1,	"GL_TEXTURE_CUBE_MAP_NEGATIVE_X"),	# 0x8516
    ("",	X,	1,	"GL_TEXTURE_CUBE_MAP_POSITIVE_Y"),	# 0x8517
    ("",	X,	1,	"GL_TEXTURE_CUBE_MAP_NEGATIVE_Y"),	# 0x8518
    ("",	X,	1,	"GL_TEXTURE_CUBE_MAP_POSITIVE_Z"),	# 0x8519
    ("",	X,	1,	"GL_TEXTURE_CUBE_MAP_NEGATIVE_Z"),	# 0x851A
    ("glGet",	I,	1,	"GL_MAX_CUBE_MAP_TEXTURE_SIZE"),	# 0x851C
    ("",	X,	1,	"GL_COMBINE"),	# 0x8570
    ("glGetTexEnv",	E,	1,	"GL_COMBINE_RGB"),	# 0x8571
    ("glGetTexEnv",	E,	1,	"GL_COMBINE_ALPHA"),	# 0x8572
    ("glGetTexEnv",	F,	1,	"GL_RGB_SCALE"),	# 0x8573
    ("",	X,	1,	"GL_ADD_SIGNED"),	# 0x8574
    ("",	X,	1,	"GL_INTERPOLATE"),	# 0x8575
    ("",	X,	1,	"GL_CONSTANT"),	# 0x8576
    ("",	X,	1,	"GL_PRIMARY_COLOR"),	# 0x8577
    ("",	X,	1,	"GL_PREVIOUS"),	# 0x8578
    ("glGetTexEnv",	E,	1,	"GL_SRC0_RGB"),	# 0x8580
    ("glGetTexEnv",	E,	1,	"GL_SRC1_RGB"),	# 0x8581
    ("glGetTexEnv",	E,	1,	"GL_SRC2_RGB"),	# 0x8582
    ("glGetTexEnv",	E,	1,	"GL_SRC0_ALPHA"),	# 0x8588
    ("glGetTexEnv",	E,	1,	"GL_SRC1_ALPHA"),	# 0x8589
    ("glGetTexEnv",	E,	1,	"GL_SRC2_ALPHA"),	# 0x858A
    ("glGetTexEnv",	E,	1,	"GL_OPERAND0_RGB"),	# 0x8590
    ("glGetTexEnv",	E,	1,	"GL_OPERAND1_RGB"),	# 0x8591
    ("glGetTexEnv",	E,	1,	"GL_OPERAND2_RGB"),	# 0x8592
    ("glGetTexEnv",	E,	1,	"GL_OPERAND0_ALPHA"),	# 0x8598
    ("glGetTexEnv",	E,	1,	"GL_OPERAND1_ALPHA"),	# 0x8599
    ("glGetTexEnv",	E,	1,	"GL_OPERAND2_ALPHA"),	# 0x859A
    ("glGet",	I,	1,	"GL_VERTEX_ARRAY_BINDING"),	# 0x85B5
    ("glGetVertexAttrib",	B,	1,	"GL_VERTEX_ATTRIB_ARRAY_ENABLED"),	# 0x8622
    ("glGetVertexAttrib",	I,	1,	"GL_VERTEX_ATTRIB_ARRAY_SIZE"),	# 0x8623
    ("glGetVertexAttrib",	I,	1,	"GL_VERTEX_ATTRIB_ARRAY_STRIDE"),	# 0x8624
    ("glGetVertexAttrib",	E,	1,	"GL_VERTEX_ATTRIB_ARRAY_TYPE"),	# 0x8625
    ("glGetVertexAttrib",	D,	4,	"GL_CURRENT_VERTEX_ATTRIB"),	# 0x8626
    ("glGetVertexAttrib",	P,	1,	"GL_VERTEX_ATTRIB_ARRAY_POINTER"),	# 0x8645
    ("glGet",	I,	1,	"GL_NUM_COMPRESSED_TEXTURE_FORMATS"),	# 0x86A2
    #XXX: the list is GL_NUM_COMPRESSED_TEXTURES
    #("glGet",	E,	1,	"GL_COMPRESSED_TEXTURE_FORMATS"),	# 0x86A3
    ("",	X,	1,	"GL_DOT3_RGB"),	# 0x86AE
    ("",	X,	1,	"GL_DOT3_RGBA"),	# 0x86AF
    ("glGetProgram",	I,	1,	"GL_PROGRAM_BINARY_LENGTH"),	# 0x8741,
    ("glGetBufferParameter",	I,	1,	"GL_BUFFER_SIZE"),	# 0x8764
    ("glGetBufferParameter",	E,	1,	"GL_BUFFER_USAGE"),	# 0x8765
    ("glGet",	I,	1,	"GL_NUM_PROGRAM_BINARY_FORMATS"),	# 0x87FE
    #XXX: the list is GL_NUM_PROGRAM_BINARY_FORMATS
    #("",	X,	1,	"GL_PROGRAM_BINARY_FORMATS"),	# 0x87FF
    ("glGet",	E,	1,	"GL_STENCIL_BACK_FUNC"),	# 0x8800
    ("glGet",	E,	1,	"GL_STENCIL_BACK_FAIL"),	# 0x8801
    ("glGet",	E,	1,	"GL_STENCIL_BACK_PASS_DEPTH_FAIL"),	# 0x8802
    ("glGet",	E,	1,	"GL_STENCIL_BACK_PASS_DEPTH_PASS"),	# 0x8803
    ("",	X,	1,	"GL_RGBA32F"),	# 0x8814
    ("",	X,	1,	"GL_RGB32F"),	# 0x8815
    ("",	X,	1,	"GL_RGBA16F"),	# 0x881A
    ("",	X,	1,	"GL_RGB16F"),	# 0x881B
    ("glGet",	I,	1,	"GL_MAX_DRAW_BUFFERS"),	# 0x8824
    ("glGet",	E,	1,	"GL_DRAW_BUFFER0"),	# 0x8825
    ("glGet",	E,	1,	"GL_DRAW_BUFFER1"),	# 0x8826
    ("glGet",	E,	1,	"GL_DRAW_BUFFER2"),	# 0x8827
    ("glGet",	E,	1,	"GL_DRAW_BUFFER3"),	# 0x8828
    ("glGet",	E,	1,	"GL_DRAW_BUFFER4"),	# 0x8829
    ("glGet",	E,	1,	"GL_DRAW_BUFFER5"),	# 0x882A
    ("glGet",	E,	1,	"GL_DRAW_BUFFER6"),	# 0x882B
    ("glGet",	E,	1,	"GL_DRAW_BUFFER7"),	# 0x882C
    ("glGet",	E,	1,	"GL_DRAW_BUFFER8"),	# 0x882D
    ("glGet",	E,	1,	"GL_DRAW_BUFFER9"),	# 0x882E
    ("glGet",	E,	1,	"GL_DRAW_BUFFER10"),	# 0x882F
    ("glGet",	E,	1,	"GL_DRAW_BUFFER11"),	# 0x8830
    ("glGet",	E,	1,	"GL_DRAW_BUFFER12"),	# 0x8831
    ("glGet",	E,	1,	"GL_DRAW_BUFFER13"),	# 0x8832
    ("glGet",	E,	1,	"GL_DRAW_BUFFER14"),	# 0x8833
    ("glGet",	E,	1,	"GL_DRAW_BUFFER15"),	# 0x8834
    ("glGet",	E,	1,	"GL_BLEND_EQUATION_ALPHA"),	# 0x883D
    ("glGetTexParameter",	E,	1,	"GL_TEXTURE_COMPARE_MODE"),	# 0x884C
    ("glGetTexParameter",	E,	1,	"GL_TEXTURE_COMPARE_FUNC"),	# 0x884D
    ("",	X,	1,	"GL_COMPARE_REF_TO_TEXTURE"),	# 0x884E
    ("glGetQuery",	I,	1,	"GL_QUERY_COUNTER_BITS_EXT"),	# 0x8864
    ("glGetQuery",	I,	1,	"GL_CURRENT_QUERY"),	# 0x8865
    ("glGetQueryObject",	I,	1,	"GL_QUERY_RESULT"),	# 0x8866
    ("glGetQueryObject",	B,	1,	"GL_QUERY_RESULT_AVAILABLE"),	# 0x8867
    ("glGet",	I,	1,	"GL_MAX_VERTEX_ATTRIBS"),	# 0x8869
    ("glGetVertexAttrib",	B,	1,	"GL_VERTEX_ATTRIB_ARRAY_NORMALIZED"),	# 0x886A
    ("glGet",	I,	1,	"GL_MAX_TESS_CONTROL_INPUT_COMPONENTS_EXT"),	# 0x886C
    ("glGet",	I,	1,	"GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS_EXT"),	# 0x886D
    ("glGet",	I,	1,	"GL_MAX_TEXTURE_IMAGE_UNITS"),	# 0x8872
    ("",	X,	1,	"GL_ARRAY_BUFFER"),	# 0x8892
    ("",	X,	1,	"GL_ELEMENT_ARRAY_BUFFER"),	# 0x8893
    ("glGet",	I,	1,	"GL_ARRAY_BUFFER_BINDING"),	# 0x8894
    ("glGet",	I,	1,	"GL_ELEMENT_ARRAY_BUFFER_BINDING"),	# 0x8895
    ("glGet",	I,	1,	"GL_VERTEX_ARRAY_BUFFER_BINDING"),	# 0x8896
    ("glGet",	I,	1,	"GL_NORMAL_ARRAY_BUFFER_BINDING"),	# 0x8897
    ("glGet",	I,	1,	"GL_COLOR_ARRAY_BUFFER_BINDING"),	# 0x8898
    ("glGet",	I,	1,	"GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING"),	# 0x889A
    ("glGetVertexAttrib",	I,	1,	"GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING"),	# 0x889F
    ("glGetBufferParameter",	B,	1,	"GL_BUFFER_MAPPED"),	# 0x88BC
    ("glGetBufferParameter",	P,	1,	"GL_BUFFER_MAP_POINTER"),	# 0x88BD
    ("glGetQuery",	I,	1,	"GL_TIME_ELAPSED_EXT"),	# 0x88BF
    ("",	X,	1,	"GL_STREAM_DRAW"),	# 0x88E0
    ("",	X,	1,	"GL_STREAM_READ"),	# 0x88E1
    ("",	X,	1,	"GL_STREAM_COPY"),	# 0x88E2
    ("",	X,	1,	"GL_STATIC_DRAW"),	# 0x88E4
    ("",	X,	1,	"GL_STATIC_READ"),	# 0x88E5
    ("",	X,	1,	"GL_STATIC_COPY"),	# 0x88E6
    ("",	X,	1,	"GL_DYNAMIC_DRAW"),	# 0x88E8
    ("",	X,	1,	"GL_DYNAMIC_READ"),	# 0x88E9
    ("",	X,	1,	"GL_DYNAMIC_COPY"),	# 0x88EA
    ("",	X,	1,	"GL_PIXEL_PACK_BUFFER"),	# 0x88EB
    ("",	X,	1,	"GL_PIXEL_UNPACK_BUFFER"),	# 0x88EC
    ("glGet",	I,	1,	"GL_PIXEL_PACK_BUFFER_BINDING"),	# 0x88ED
    ("glGet",	I,	1,	"GL_PIXEL_UNPACK_BUFFER_BINDING"),	# 0x88EF
    ("",	X,	1,	"GL_DEPTH24_STENCIL8"),	# 0x88F0
    ("glGetVertexAttrib",	B,	1,	"GL_VERTEX_ATTRIB_ARRAY_INTEGER"),	# 0x88FD
    ("glGetVertexAttrib",	I,	1,	"GL_VERTEX_ATTRIB_ARRAY_DIVISOR"),	# 0x88FE
    ("glGet",	I,	1,	"GL_MAX_ARRAY_TEXTURE_LAYERS"),	# 0x88FF
    ("glGet",	F,	1,	"GL_MIN_PROGRAM_TEXEL_OFFSET"),	# 0x8904
    ("glGet",	F,	1,	"GL_MAX_PROGRAM_TEXEL_OFFSET"),	# 0x8905
    ("glGetProgramiv",	I,	1,	"GL_GEOMETRY_LINKED_VERTICES_OUT_EXT"),	# 0x8916
    ("glGetProgramiv",	I,	1,	"GL_GEOMETRY_LINKED_INPUT_TYPE_EXT"),	# 0x8917
    ("glGetProgramiv",	I,	1,	"GL_GEOMETRY_LINKED_OUTPUT_TYPE_EXT"),	# 0x8918
    ("glGet",	I,	1,	"GL_SAMPLER_BINDING"),	# 0x8919
    #("",	X,	1,	"GL_POINT_SIZE_ARRAY_TYPE_OES"),	# 0x898A
    #("",	X,	1,	"GL_POINT_SIZE_ARRAY_STRIDE_OES"),	# 0x898B
    #("",	X,	1,	"GL_POINT_SIZE_ARRAY_POINTER_OES"),	# 0x898C
    #("",	X,	1,	"GL_MODELVIEW_MATRIX_FLOAT_AS_INT_BITS_OES"),	# 0x898D
    #("",	X,	1,	"GL_PROJECTION_MATRIX_FLOAT_AS_INT_BITS_OES"),	# 0x898E
    #("",	X,	1,	"GL_TEXTURE_MATRIX_FLOAT_AS_INT_BITS_OES"),	# 0x898F
    ("",	X,	1,	"GL_UNIFORM_BUFFER"),	# 0x8A11
    ("",	X,	1,	"GL_RGB_422_APPLE"),	# 0x8A1F
    ("glGet",	I,	1,	"GL_UNIFORM_BUFFER_BINDING"),	# 0x8A28
    ("glGet",	I,	1,	"GL_UNIFORM_BUFFER_START"),	# 0x8A29
    ("glGet",	I,	1,	"GL_UNIFORM_BUFFER_SIZE"),	# 0x8A2A
    ("glGet",	I,	1,	"GL_MAX_VERTEX_UNIFORM_BLOCKS"),	# 0x8A2B
    ("glGet",	I,	1,	"GL_MAX_GEOMETRY_UNIFORM_BLOCKS_EXT"),	# 0x8A2C
    ("glGet",	I,	1,	"GL_MAX_FRAGMENT_UNIFORM_BLOCKS"),	# 0x8A2D
    ("glGet",	I,	1,	"GL_MAX_COMBINED_UNIFORM_BLOCKS"),	# 0x8A2E
    ("glGet",	I,	1,	"GL_MAX_UNIFORM_BUFFER_BINDINGS"),	# 0x8A2F
    ("glGet",	I,	1,	"GL_MAX_UNIFORM_BLOCK_SIZE"),	# 0x8A30
    ("glGet",	I,	1,	"GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS"),	# 0x8A31
    ("glGet",	I,	1,	"GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS_EXT"),	# 0x8A32
    ("glGet",	I,	1,	"GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS"),	# 0x8A33
    ("glGet",	I,	1,	"GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT"),	# 0x8A34
    ("glGetProgram",	I,	1,	"GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH"),	# 0x8A35
    ("glGetProgram",	I,	1,	"GL_ACTIVE_UNIFORM_BLOCKS"),	# 0x8A36
    ("glGetActiveUniforms",	E,	1,	"GL_UNIFORM_TYPE"),	# 0x8A37
    ("glGetActiveUniforms",	I,	1,	"GL_UNIFORM_SIZE"),	# 0x8A38
    ("glGetActiveUniforms",	I,	1,	"GL_UNIFORM_NAME_LENGTH"),	# 0x8A39
    ("glGetActiveUniforms",	I,	1,	"GL_UNIFORM_BLOCK_INDEX"),	# 0x8A3A
    ("glGetActiveUniforms",	I,	1,	"GL_UNIFORM_OFFSET"),	# 0x8A3B
    ("glGetActiveUniforms",	I,	1,	"GL_UNIFORM_ARRAY_STRIDE"),	# 0x8A3C
    ("glGetActiveUniforms",	I,	1,	"GL_UNIFORM_MATRIX_STRIDE"),	# 0x8A3D
    ("glGetActiveUniforms",	B,	1,	"GL_UNIFORM_IS_ROW_MAJOR"),	# 0x8A3E
    ("glGetActiveUniformBlock",	I,	1,	"GL_UNIFORM_BLOCK_BINDING"),	# 0x8A3F
    ("glGetActiveUniformBlock",	I,	1,	"GL_UNIFORM_BLOCK_DATA_SIZE"),	# 0x8A40
    ("glGetActiveUniformBlock",	I,	1,	"GL_UNIFORM_BLOCK_NAME_LENGTH"),	# 0x8A41
    ("glGetActiveUniformBlock",	I,	1,	"GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS"),	# 0x8A42
    ("glGetActiveUniformBlock",	I,	1,	"GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES"),	# 0x8A43
    ("glGetActiveUniformBlock",	B,	1,	"GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER"),	# 0x8A44
    ("glGetActiveUniformBlock",	B,	1,	"GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER"),	# 0x8A46
    ("glGetTexParameter",	E,	1,	"GL_TEXTURE_SRGB_DECODE_EXT"),	# 0x8A48
    ("",	X,	1,	"GL_DECODE_EXT"),	# 0x8A49
    ("",	X,	1,	"GL_SKIP_DECODE_EXT"),	# 0x8A4A
    ("glGetProgramPipeline",	I,	1,	"GL_FRAGMENT_SHADER"),	# 0x8B30
    ("glGetProgramPipeline",	I,	1,	"GL_VERTEX_SHADER"),	# 0x8B31
    ("glGet",	I,	1,	"GL_MAX_FRAGMENT_UNIFORM_COMPONENTS"),	# 0x8B49
    ("glGet",	I,	1,	"GL_MAX_VERTEX_UNIFORM_COMPONENTS"),	# 0x8B4A
    ("glGet",	I,	1,	"GL_MAX_VARYING_COMPONENTS"),	# 0x8B4B
    ("glGet",	I,	1,	"GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS"),	# 0x8B4C
    ("glGet",	I,	1,	"GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS"),	# 0x8B4D
    ("glGetShader",	E,	1,	"GL_SHADER_TYPE"),	# 0x8B4F
    ("",	X,	1,	"GL_FLOAT_VEC2"),	# 0x8B50
    ("",	X,	1,	"GL_FLOAT_VEC3"),	# 0x8B51
    ("",	X,	1,	"GL_FLOAT_VEC4"),	# 0x8B52
    ("",	X,	1,	"GL_INT_VEC2"),	# 0x8B53
    ("",	X,	1,	"GL_INT_VEC3"),	# 0x8B54
    ("",	X,	1,	"GL_INT_VEC4"),	# 0x8B55
    ("",	X,	1,	"GL_BOOL"),	# 0x8B56
    ("",	X,	1,	"GL_BOOL_VEC2"),	# 0x8B57
    ("",	X,	1,	"GL_BOOL_VEC3"),	# 0x8B58
    ("",	X,	1,	"GL_BOOL_VEC4"),	# 0x8B59
    ("",	X,	1,	"GL_FLOAT_MAT2"),	# 0x8B5A
    ("",	X,	1,	"GL_FLOAT_MAT3"),	# 0x8B5B
    ("",	X,	1,	"GL_FLOAT_MAT4"),	# 0x8B5C
    ("",	X,	1,	"GL_SAMPLER_2D"),	# 0x8B5E
    ("",	X,	1,	"GL_SAMPLER_3D"),	# 0x8B5F
    ("",	X,	1,	"GL_SAMPLER_CUBE"),	# 0x8B60
    ("",	X,	1,	"GL_SAMPLER_2D_SHADOW"),	# 0x8B62
    ("",	X,	1,	"GL_FLOAT_MAT2x3"),	# 0x8B65
    ("",	X,	1,	"GL_FLOAT_MAT2x4"),	# 0x8B66
    ("",	X,	1,	"GL_FLOAT_MAT3x2"),	# 0x8B67
    ("",	X,	1,	"GL_FLOAT_MAT3x4"),	# 0x8B68
    ("",	X,	1,	"GL_FLOAT_MAT4x2"),	# 0x8B69
    ("",	X,	1,	"GL_FLOAT_MAT4x3"),	# 0x8B6A
    ("glGetShader,glGetProgram",	B,	1,	"GL_DELETE_STATUS"),	# 0x8B80
    ("glGetShader,glGetProgram",	B,	1,	"GL_COMPILE_STATUS"),	# 0x8B81
    ("glGetShader,glGetProgram",	B,	1,	"GL_LINK_STATUS"),	# 0x8B82
    ("glGetShader,glGetProgram",	B,	1,	"GL_VALIDATE_STATUS"),	# 0x8B83
    ("glGetShader,glGetProgram",	I,	1,	"GL_INFO_LOG_LENGTH"),	# 0x8B84
    ("glGetProgram",	I,	1,	"GL_ATTACHED_SHADERS"),	# 0x8B85
    ("glGetProgram",	I,	1,	"GL_ACTIVE_UNIFORMS"),	# 0x8B86
    ("glGetProgram",	I,	1,	"GL_ACTIVE_UNIFORM_MAX_LENGTH"),	# 0x8B87
    ("glGetShader",	I,	1,	"GL_SHADER_SOURCE_LENGTH"),	# 0x8B88
    ("glGetProgram",	I,	1,	"GL_ACTIVE_ATTRIBUTES"),	# 0x8B89
    ("glGetProgram",	I,	1,	"GL_ACTIVE_ATTRIBUTE_MAX_LENGTH"),	# 0x8B8A
    ("",	X,	1,	"GL_FRAGMENT_SHADER_DERIVATIVE_HINT"),	# 0x8B8B
    ("glGet",	S,	1,	"GL_SHADING_LANGUAGE_VERSION"),	# 0x8B8C
    ("glGet",	I,	1,	"GL_CURRENT_PROGRAM"),	# 0x8B8D
    #("",	X,	1,	"GL_PALETTE4_RGB8_OES"),	# 0x8B90
    #("",	X,	1,	"GL_PALETTE4_RGBA8_OES"),	# 0x8B91
    #("",	X,	1,	"GL_PALETTE4_R5_G6_B5_OES"),	# 0x8B92
    #("",	X,	1,	"GL_PALETTE4_RGBA4_OES"),	# 0x8B93
    #("",	X,	1,	"GL_PALETTE4_RGB5_A1_OES"),	# 0x8B94
    #("",	X,	1,	"GL_PALETTE8_RGB8_OES"),	# 0x8B95
    #("",	X,	1,	"GL_PALETTE8_RGBA8_OES"),	# 0x8B96
    #("",	X,	1,	"GL_PALETTE8_R5_G6_B5_OES"),	# 0x8B97
    #("",	X,	1,	"GL_PALETTE8_RGBA4_OES"),	# 0x8B98
    #("",	X,	1,	"GL_PALETTE8_RGB5_A1_OES"),	# 0x8B99
    ("glGet",	I,	1,	"GL_IMPLEMENTATION_COLOR_READ_TYPE"),	# 0x8B9A
    ("glGet",	I,	1,	"GL_IMPLEMENTATION_COLOR_READ_FORMAT"),	# 0x8B9B
    #("",	X,	1,	"GL_POINT_SIZE_ARRAY_OES"),	# 0x8B9C
    ("",	I,	4,	"GL_TEXTURE_CROP_RECT_OES"),	# 0x8B9D
    #("",	X,	1,	"GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES"),	# 0x8B9E
    #("",	X,	1,	"GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES"),	# 0x8B9F
    ("",	X,	1,	"GL_COUNTER_TYPE_AMD"),	# 0x8BC0
    ("",	X,	1,	"GL_COUNTER_RANGE_AMD"),	# 0x8BC1
    ("",	X,	1,	"GL_UNSIGNED_INT64_AMD"),	# 0x8BC2
    ("",	X,	1,	"GL_PERCENTAGE_AMD"),	# 0x8BC3
    ("",	X,	1,	"GL_PERFMON_RESULT_AVAILABLE_AMD"),	# 0x8BC4
    ("",	X,	1,	"GL_PERFMON_RESULT_SIZE_AMD"),	# 0x8BC5
    ("",	X,	1,	"GL_PERFMON_RESULT_AMD"),	# 0x8BC6
    #("",	X,	1,	"GL_TEXTURE_WIDTH_QCOM"),	# 0x8BD2
    #("",	X,	1,	"GL_TEXTURE_HEIGHT_QCOM"),	# 0x8BD3
    #("",	X,	1,	"GL_TEXTURE_DEPTH_QCOM"),	# 0x8BD4
    #("",	X,	1,	"GL_TEXTURE_INTERNAL_FORMAT_QCOM"),	# 0x8BD5
    #("",	X,	1,	"GL_TEXTURE_FORMAT_QCOM"),	# 0x8BD6
    #("",	X,	1,	"GL_TEXTURE_TYPE_QCOM"),	# 0x8BD7
    #("",	X,	1,	"GL_TEXTURE_IMAGE_VALID_QCOM"),	# 0x8BD8
    #("",	X,	1,	"GL_TEXTURE_NUM_LEVELS_QCOM"),	# 0x8BD9
    #("",	X,	1,	"GL_TEXTURE_TARGET_QCOM"),	# 0x8BDA
    #("",	X,	1,	"GL_TEXTURE_OBJECT_VALID_QCOM"),	# 0x8BDB
    #("",	X,	1,	"GL_STATE_RESTORE"),	# 0x8BDC
    #("",	X,	1,	"GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG"),	# 0x8C00
    #("",	X,	1,	"GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG"),	# 0x8C01
    #("",	X,	1,	"GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG"),	# 0x8C02
    #("",	X,	1,	"GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG"),	# 0x8C03
    #("",	X,	1,	"GL_MODULATE_COLOR_IMG"),	# 0x8C04
    #("",	X,	1,	"GL_RECIP_ADD_SIGNED_ALPHA_IMG"),	# 0x8C05
    #("",	X,	1,	"GL_TEXTURE_ALPHA_MODULATE_IMG"),	# 0x8C06
    #("",	X,	1,	"GL_FACTOR_ALPHA_MODULATE_IMG"),	# 0x8C07
    #("",	X,	1,	"GL_FRAGMENT_ALPHA_MODULATE_IMG"),	# 0x8C08
    #("",	X,	1,	"GL_ADD_BLEND_IMG"),	# 0x8C09
    #("",	X,	1,	"GL_SGX_BINARY_IMG"),	# 0x8C0A
    ("",	X,	1,	"GL_UNSIGNED_NORMALIZED"),	# 0x8C17
    ("",	X,	1,	"GL_TEXTURE_2D_ARRAY"),	# 0x8C1A
    ("_glGet",	I,	1,	"GL_TEXTURE_BINDING_2D_ARRAY"),	# 0x8C1D
    ("glGet",	I,	1,	"GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT"),	#0x8C29
    ("glGet",	I,	1,	"GL_TEXTURE_BUFFER_EXT"),	# 0x8C2A
    ("glGet",	I,	1,	"GL_MAX_TEXTURE_BUFFER_SIZE_EXT"),	# 0x8C2B
    ("glGet",	I,	1,	"GL_TEXTURE_BINDING_BUFFER_EXT"),	# 0x8C2C
    ("glGetTexLevelParameter",	I,	1,	"GL_TEXTURE_BUFFER_DATA_STORE_BINDING_EXT"),	# 0x8C2D
    ("",	X,	1,	"GL_ANY_SAMPLES_PASSED"),	# 0x8C2F
    ("glGet",	B,	1,	"GL_SAMPLE_SHADING_OES"),	# 0x8C36
    ("glGet",	F,	1,	"GL_MIN_SAMPLE_SHADING_VALUE_OES"),	# 0x8C37
    ("",	X,	1,	"GL_R11F_G11F_B10F"),	# 0x8C3A
    ("",	X,	1,	"GL_UNSIGNED_INT_10F_11F_11F_REV"),	# 0x8C3B
    ("",	X,	1,	"GL_RGB9_E5"),	# 0x8C3D
    ("",	X,	1,	"GL_UNSIGNED_INT_5_9_9_9_REV"),	# 0x8C3E
    ("",	X,	1,	"GL_SRGB"),	# 0x8C40
    ("",	X,	1,	"GL_SRGB8"),	# 0x8C41
    ("",	X,	1,	"GL_SRGB8_ALPHA8"),	# 0x8C43
    ("glGetProgram",	I,	1,	"GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH"),	# 0x8C76
    ("glGetProgram",	E,	1,	"GL_TRANSFORM_FEEDBACK_BUFFER_MODE"),	# 0x8C7F
    ("glGet",   I,      1,      "GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS"),       # 0x8C80
    ("",	X,	1,	"GL_TRANSFORM_FEEDBACK_VARYINGS"),	# 0x8C83
    ("",	X,	1,	"GL_TRANSFORM_FEEDBACK_BUFFER_START"),	# 0x8C84
    ("",	X,	1,	"GL_TRANSFORM_FEEDBACK_BUFFER_SIZE"),	# 0x8C85
    ("glGetQueryiv",	I,	1,	"GL_PRIMITIVES_GENERATED_EXT"),	# 0x8C87
    ("",	X,	1,	"GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN"),	# 0x8C88
    ("",	X,	1,	"GL_RASTERIZER_DISCARD"),	# 0x8C89
    ("glGet",   I,      1,      "GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS"),    # 0x8C8A
    ("glGet",   I,      1,      "GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS"),  # 0x8C8B
    ("",	X,	1,	"GL_INTERLEAVED_ATTRIBS"),	# 0x8C8C
    ("",	X,	1,	"GL_SEPARATE_ATTRIBS"),	# 0x8C8D
    ("",	X,	1,	"GL_TRANSFORM_FEEDBACK_BUFFER"),	# 0x8C8E
    ("glGet",	I,	1,	"GL_TRANSFORM_FEEDBACK_BUFFER_BINDING"),	# 0x8C8F
    #("",	X,	1,	"GL_ATC_RGB_AMD"),	# 0x8C92
    #("",	X,	1,	"GL_ATC_RGBA_EXPLICIT_ALPHA_AMD"),	# 0x8C93
    ("",	X,	1,	"GL_STENCIL_BACK_REF"),	# 0x8CA3
    ("",	X,	1,	"GL_STENCIL_BACK_VALUE_MASK"),	# 0x8CA4
    ("",	X,	1,	"GL_STENCIL_BACK_WRITEMASK"),	# 0x8CA5
    #("glGet",	I,	1,	"GL_DRAW_FRAMEBUFFER_BINDING"),	# 0x8CA6
    ("glGet",	I,	1,	"GL_RENDERBUFFER_BINDING"),	# 0x8CA7
    ("",	I,	1,	"GL_READ_FRAMEBUFFER"),	# 0x8CA8
    ("",	I,	1,	"GL_DRAW_FRAMEBUFFER"),	# 0x8CA9
    ("glGet",	I,	1,	"GL_READ_FRAMEBUFFER_BINDING"),	# 0x8CAA
    ("glGetRenderbufferParameter",	I,	1,	"GL_RENDERBUFFER_SAMPLES"),	# 0x8CAB
    ("",	X,	1,	"GL_DEPTH_COMPONENT32F"),	# 0x8CAC
    ("",	X,	1,	"GL_DEPTH32F_STENCIL8"),	# 0x8CAD
    ("glGetFramebufferAttachmentParameter",	E,	1,	"GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE"),	# 0x8CD0
    ("glGetFramebufferAttachmentParameter",	I,	1,	"GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME"),	# 0x8CD1
    ("glGetFramebufferAttachmentParameter",	I,	1,	"GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL"),	# 0x8CD2
    ("glGetFramebufferAttachmentParameter",	E,	1,	"GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE"),	# 0x8CD3
    ("glGetFramebufferAttachmentParameter",	I,	1,	"GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER"),	# 0x8CD4
    ("",	X,	1,	"GL_FRAMEBUFFER_COMPLETE"),	# 0x8CD5
    ("",	X,	1,	"GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT"),	# 0x8CD6
    ("",	X,	1,	"GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT"),	# 0x8CD7
    ("",	X,	1,	"GL_FRAMEBUFFER_UNSUPPORTED"),	# 0x8CDD
    ("glGet",	I,	1,	"GL_MAX_COLOR_ATTACHMENTS"),	# 0x8CDF
    ("",	X,	1,	"GL_COLOR_ATTACHMENT0"),	# 0x8CE0
    ("",	X,	1,	"GL_COLOR_ATTACHMENT0"),	# 0x8CE0
    ("",	X,	1,	"GL_COLOR_ATTACHMENT1"),	# 0x8CE1
    ("",	X,	1,	"GL_COLOR_ATTACHMENT2"),	# 0x8CE2
    ("",	X,	1,	"GL_COLOR_ATTACHMENT3"),	# 0x8CE3
    ("",	X,	1,	"GL_COLOR_ATTACHMENT4"),	# 0x8CE4
    ("",	X,	1,	"GL_COLOR_ATTACHMENT5"),	# 0x8CE5
    ("",	X,	1,	"GL_COLOR_ATTACHMENT6"),	# 0x8CE6
    ("",	X,	1,	"GL_COLOR_ATTACHMENT7"),	# 0x8CE7
    ("",	X,	1,	"GL_COLOR_ATTACHMENT8"),	# 0x8CE8
    ("",	X,	1,	"GL_COLOR_ATTACHMENT9"),	# 0x8CE9
    ("",	X,	1,	"GL_COLOR_ATTACHMENT10"),	# 0x8CEA
    ("",	X,	1,	"GL_COLOR_ATTACHMENT11"),	# 0x8CEB
    ("",	X,	1,	"GL_COLOR_ATTACHMENT12"),	# 0x8CEC
    ("",	X,	1,	"GL_COLOR_ATTACHMENT13"),	# 0x8CED
    ("",	X,	1,	"GL_DEPTH_ATTACHMENT"),	# 0x8D00
    ("",	X,	1,	"GL_STENCIL_ATTACHMENT"),	# 0x8D20
    ("",	X,	1,	"GL_FRAMEBUFFER"),	# 0x8D40
    ("",	X,	1,	"GL_RENDERBUFFER"),	# 0x8D41
    ("glGetRenderbufferParameter",	I,	1,	"GL_RENDERBUFFER_WIDTH"),	# 0x8D42
    ("glGetRenderbufferParameter",	I,	1,	"GL_RENDERBUFFER_HEIGHT"),	# 0x8D43
    ("glGetRenderbufferParameter",	E,	1,	"GL_RENDERBUFFER_INTERNAL_FORMAT"),	# 0x8D44
    ("",	X,	1,	"GL_STENCIL_INDEX8"),	# 0x8D48
    ("glGetRenderbufferParameter",	I,	1,	"GL_RENDERBUFFER_RED_SIZE"),	# 0x8D50
    ("glGetRenderbufferParameter",	I,	1,	"GL_RENDERBUFFER_GREEN_SIZE"),	# 0x8D51
    ("glGetRenderbufferParameter",	I,	1,	"GL_RENDERBUFFER_BLUE_SIZE"),	# 0x8D52
    ("glGetRenderbufferParameter",	I,	1,	"GL_RENDERBUFFER_ALPHA_SIZE"),	# 0x8D53
    ("glGetRenderbufferParameter",	I,	1,	"GL_RENDERBUFFER_DEPTH_SIZE"),	# 0x8D54
    ("glGetRenderbufferParameter",	I,	1,	"GL_RENDERBUFFER_STENCIL_SIZE"),	# 0x8D55
    ("",	X,	1,	"GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE"),	# 0x8D56
    ("glGet",	I,	1,	"GL_MAX_SAMPLES"),	# 0x8D57
    #("",	X,	1,	"GL_TEXTURE_GEN_STR_OES"),	# 0x8D60
    #("",	X,	1,	"GL_HALF_FLOAT_OES"),	# 0x8D61
    #("",	X,	1,	"GL_RGB565_OES"),	# 0x8D62
    #("",	X,	1,	"GL_ETC1_RGB8_OES"),	# 0x8D64
    #("",	X,	1,	"GL_TEXTURE_EXTERNAL_OES"),	# 0x8D65
    #("",	X,	1,	"GL_SAMPLER_EXTERNAL_OES"),	# 0x8D66
    ("",	X,	1,	"GL_TEXTURE_BINDING_EXTERNAL_OES"),	# 0x8D67
    #("",	X,	1,	"GL_REQUIRED_TEXTURE_IMAGE_UNITS_OES"),	# 0x8D68
    ("",	X,	1,	"GL_RGBA32UI"),	# 0x8D70
    ("",	X,	1,	"GL_RGB32UI"),	# 0x8D71
    ("",	X,	1,	"GL_RGBA16UI"),	# 0x8D76
    ("",	X,	1,	"GL_RGB16UI"),	# 0x8D77
    ("",	X,	1,	"GL_RGBA8UI"),	# 0x8D7C
    ("",	X,	1,	"GL_RGB8UI"),	# 0x8D7D
    ("",	X,	1,	"GL_RGBA32I"),	# 0x8D82
    ("",	X,	1,	"GL_RGB32I"),	# 0x8D83
    ("",	X,	1,	"GL_RGBA16I"),	# 0x8D88
    ("",	X,	1,	"GL_RGB16I"),	# 0x8D89
    ("",	X,	1,	"GL_RGBA8I"),	# 0x8D8E
    ("",	X,	1,	"GL_RGB8I"),	# 0x8D8F
    ("",	X,	1,	"GL_RED_INTEGER"),	# 0x8D94
    ("",	X,	1,	"GL_RGB_INTEGER"),	# 0x8D98
    ("",	X,	1,	"GL_RGBA_INTEGER"),	# 0x8D99
    ("",	X,	1,	"GL_INT_2_10_10_10_REV"),	# 0x8D9F
    ("glGetFramebufferAttachmentParameter",	B,	1,	"GL_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT"),	# 0x8DA7
    ("",	X,	1,	"GL_FLOAT_32_UNSIGNED_INT_24_8_REV"),	# 0x8DAD
    ("",	X,	1,	"GL_SAMPLER_2D_ARRAY"),	# 0x8DC1
    ("",	X,	1,	"GL_SAMPLER_2D_ARRAY_SHADOW"),	# 0x8DC4
    ("",	X,	1,	"GL_SAMPLER_CUBE_SHADOW"),	# 0x8DC5
    ("",	X,	1,	"GL_UNSIGNED_INT_VEC2"),	# 0x8DC6
    ("",	X,	1,	"GL_UNSIGNED_INT_VEC3"),	# 0x8DC7
    ("",	X,	1,	"GL_UNSIGNED_INT_VEC4"),	# 0x8DC8
    ("",	X,	1,	"GL_INT_SAMPLER_2D"),	# 0x8DCA
    ("",	X,	1,	"GL_INT_SAMPLER_3D"),	# 0x8DCB
    ("",	X,	1,	"GL_INT_SAMPLER_CUBE"),	# 0x8DCC
    ("",	X,	1,	"GL_INT_SAMPLER_2D_ARRAY"),	# 0x8DCF
    ("",	X,	1,	"GL_UNSIGNED_INT_SAMPLER_2D"),	# 0x8DD2
    ("",	X,	1,	"GL_UNSIGNED_INT_SAMPLER_3D"),	# 0x8DD3
    ("",	X,	1,	"GL_UNSIGNED_INT_SAMPLER_CUBE"),	# 0x8DD4
    ("",	X,	1,	"GL_UNSIGNED_INT_SAMPLER_2D_ARRAY"),	# 0x8DD7
    ("glGetProgramPipeline",	I,	1,	"GL_GEOMETRY_SHADER_EXT"),	# 0x8DD9
    ("glGet",	I,	1,	"GL_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT"),	# 0x8DDF
    ("",	X,	1,	"GL_LOW_FLOAT"),	# 0x8DF0
    ("",	X,	1,	"GL_MEDIUM_FLOAT"),	# 0x8DF1
    ("",	X,	1,	"GL_HIGH_FLOAT"),	# 0x8DF2
    ("",	X,	1,	"GL_LOW_INT"),	# 0x8DF3
    ("",	X,	1,	"GL_MEDIUM_INT"),	# 0x8DF4
    ("",	X,	1,	"GL_HIGH_INT"),	# 0x8DF5
    ("glGet",	I,	1,	"GL_NUM_SHADER_BINARY_FORMATS"),	# 0x8DF9
    ("glGet",	B,	1,	"GL_SHADER_COMPILER"),	# 0x8DFA
    ("glGet",	I,	1,	"GL_MAX_VERTEX_UNIFORM_VECTORS"),	# 0x8DFB
    ("glGet",	I,	1,	"GL_MAX_VARYING_VECTORS"),	# 0x8DFC
    ("glGet",	I,	1,	"GL_MAX_FRAGMENT_UNIFORM_VECTORS"),	# 0x8DFD
    ("glGet",	I,	1,	"GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS_EXT"),	# 0x8E1E
    ("glGet",	I,	1,	"GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS_EXT"),	# 0x8E1F
    ("",	X,	1,	"GL_TRANSFORM_FEEDBACK"),	# 0x8E22
    ("glGet",	I,	1,	"GL_TRANSFORM_FEEDBACK_BINDING"),	# 0x8E25
    ("glGet",	I,	1,	"GL_TIMESTAMP_EXT"),	# 0x8E28
    ("glGetTexParameter",	E,	1,	"GL_TEXTURE_SWIZZLE_R"),	# 0x8E42
    ("glGetTexParameter",	E,	1,	"GL_TEXTURE_SWIZZLE_G"),	# 0x8E43
    ("glGetTexParameter",	E,	1,	"GL_TEXTURE_SWIZZLE_B"),	# 0x8E44
    ("glGetTexParameter",	E,	1,	"GL_TEXTURE_SWIZZLE_A"),	# 0x8E45
    ("glGet",	F,	1,	"GL_MIN_FRAGMENT_INTERPOLATION_OFFSET"),	# 0x8E5B
    ("glGet",	F,	1,	"GL_MAX_FRAGMENT_INTERPOLATION_OFFSET"),	# 0x8E5C
    ("glGet",	I,	1,	"GL_FRAGMENT_INTERPOLATION_OFFSET_BITS"),	# 0x8E5D
    ("glGet",	I,	1,	"GL_PATCH_VERTICES_EXT"),	# 0x8E72
    ("glGetProgram",	I,	1,	"GL_TESS_CONTROL_OUTPUT_VERTICES_EXT"),	# 0x8E75
    ("glGetProgram",	E,	1,	"GL_TESS_GEN_MODE_EXT"),	# 0x8E76
    ("glGetProgram",	E,	1,	"GL_TESS_GEN_SPACING_EXT"),	# 0x8E77
    ("glGetProgram",	E,	1,	"GL_TESS_GEN_VERTEX_ORDER_EXT"),	# 0x8E78
    ("glGetProgram",	E,	1,	"GL_TESS_GEN_POINT_MODE_EXT"),	# 0x8E79
    ("glGet",	I,	1,	"GL_MAX_PATCH_VERTICES_EXT"),	# 0x8E7D
    ("glGet",	I,	1,	"GL_MAX_TESS_GEN_LEVEL_EXT"),	# 0x8E7E
    ("glGet",	I,	1,	"GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS_EXT"),	# 0x8E7F
    ("glGet",	I,	1,	"GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS_EXT"),	# 0x8E80
    ("glGet",	I,	1,	"GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS_EXT"),	# 0x8E81
    ("glGet",	I,	1,	"GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS_EXT"),	# 0x8E82
    ("glGet",	I,	1,	"GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS_EXT"),	# 0x8E83
    ("glGet",	I,	1,	"GL_MAX_TESS_PATCH_COMPONENTS_EXT"),	# 0x8E84
    ("glGet",	I,	1,	"GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS_EXT"),	# 0x8E85
    ("glGet",	I,	1,	"GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS_EXT"),	# 0x8E86
    ("glGetProgramPipeline",	I,	1,	"GL_TESS_EVALUATION_SHADER_EXT"),	# 0x8E87
    ("glGetProgramPipeline",	I,	1,	"GL_TESS_CONTROL_SHADER_EXT"),	# 0x8E88
    ("glGet",	I,	1,	"GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS_EXT"),	# 0x8E89
    ("glGet",	I,	1,	"GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS_EXT"),	# 0x8E8A
    #("",	X,	1,	"GL_COVERAGE_COMPONENT_NV"),	# 0x8ED0
    #("",	X,	1,	"GL_COVERAGE_COMPONENT4_NV"),	# 0x8ED1
    #("",	X,	1,	"GL_COVERAGE_ATTACHMENT_NV"),	# 0x8ED2
    #("",	X,	1,	"GL_COVERAGE_BUFFERS_NV"),	# 0x8ED3
    #("",	X,	1,	"GL_COVERAGE_SAMPLES_NV"),	# 0x8ED4
    #("",	X,	1,	"GL_COVERAGE_ALL_FRAGMENTS_NV"),	# 0x8ED5
    #("",	X,	1,	"GL_COVERAGE_EDGE_FRAGMENTS_NV"),	# 0x8ED6
    #("",	X,	1,	"GL_COVERAGE_AUTOMATIC_NV"),	# 0x8ED7
    ("glGet",	I,	1,	"GL_COPY_READ_BUFFER"),	# 0x8F36
    ("glGet",	I,	1,	"GL_COPY_WRITE_BUFFER"),	# 0x8F37
    #("",	X,	1,	"GL_MALI_SHADER_BINARY_ARM"),	# 0x8F60
    ("",	X,	1,	"GL_R8_SNORM"),	# 0x8F94
    ("",	X,	1,	"GL_RG8_SNORM"),	# 0x8F95
    ("",	X,	1,	"GL_RGB8_SNORM"),	# 0x8F96
    ("",	X,	1,	"GL_RGBA8_SNORM"),	# 0x8F97
    ("",	X,	1,	"GL_SIGNED_NORMALIZED"),	# 0x8F9C
    #("",	X,	1,	"GL_PERFMON_GLOBAL_MODE_QCOM"),	# 0x8FA0
    ("glGet",	I,	1,	"GL_GPU_DISJOINT_EXT"),	# 0x8FBB
    #("",	X,	1,	"GL_SHADER_BINARY_VIV"),	# 0x8FC4
    ("glGet",	B,	1,	"GL_TEXTURE_CUBE_MAP_ARRAY_EXT"),	# 0x9009
    ("glGet",	I,	1,	"GL_TEXTURE_BINDING_CUBE_MAP_ARRAY_EXT"),	# 0x900A
    ("",	X,	1,	"GL_SAMPLER_CUBE_MAP_ARRAY_EXT"),	# 0x900C
    ("",	X,	1,	"GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW_EXT"),	# 0x900D
    ("",	X,	1,	"GL_INT_SAMPLER_CUBE_MAP_ARRAY_EXT"),	# 0x900E
    ("",	X,	1,	"GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY_EXT"),	# 0x900F
    ("",	X,	1,	"GL_IMAGE_CUBE_MAP_ARRAY_EXT"),	# 0x9054
    ("",	X,	1,	"GL_INT_IMAGE_CUBE_MAP_ARRAY_EXT"),	# 0x905F
    ("",	X,	1,	"GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY_EXT"),	# 0x906A
    ("",	X,	1,	"GL_RGB10_A2UI"),	# 0x906F
    ("_glGet",	I64,	1,	"GL_MAX_SERVER_WAIT_TIMEOUT"),	# 0x9111
    ("",	X,	1,	"GL_OBJECT_TYPE"),	# 0x9112
    ("",	X,	1,	"GL_SYNC_CONDITION"),	# 0x9113
    ("",	X,	1,	"GL_SYNC_STATUS"),	# 0x9114
    ("",	X,	1,	"GL_SYNC_FLAGS"),	# 0x9115
    ("",	X,	1,	"GL_SYNC_FENCE"),	# 0x9116
    ("",	X,	1,	"GL_SYNC_GPU_COMMANDS_COMPLETE"),	# 0x9117
    ("",	X,	1,	"GL_UNSIGNALED"),	# 0x9118
    ("",	X,	1,	"GL_SIGNALED"),	# 0x9119
    ("",	X,	1,	"GL_ALREADY_SIGNALED"),	# 0x911A
    ("",	X,	1,	"GL_TIMEOUT_EXPIRED"),	# 0x911B
    ("",	X,	1,	"GL_CONDITION_SATISFIED"),	# 0x911C
    ("",	X,	1,	"GL_WAIT_FAILED"),	# 0x911D
    ("glGetBufferParameter",	I,	1,	"GL_BUFFER_ACCESS_FLAGS"),	# 0x911F
    ("glGetBufferParameter",	I,	1,	"GL_BUFFER_MAP_LENGTH"),	# 0x9120
    ("glGetBufferParameter",	I,	1,	"GL_BUFFER_MAP_OFFSET"),	# 0x9121
    ("glGet",   I,      1,      "GL_MAX_VERTEX_OUTPUT_COMPONENTS"),     # 0x9122
    ("glGet",	I,	1,	"GL_MAX_GEOMETRY_INPUT_COMPONENTS_EXT"),	# 0x9123
    ("glGet",	I,	1,	"GL_MAX_GEOMETRY_OUTPUT_COMPONENTS_EXT"),	# 0x9124
    ("glGet",   I,      1,      "GL_MAX_FRAGMENT_INPUT_COMPONENTS"),    # 0x9125
    ("glGetTexParameter",	B,	1,	"GL_TEXTURE_IMMUTABLE_FORMAT"),	# 0x912F
    #("",	X,	1,	"GL_SGX_PROGRAM_BINARY_IMG"),	# 0x9130
    #("",	X,	1,	"GL_RENDERBUFFER_SAMPLES_IMG"),	# 0x9133
    #("",	X,	1,	"GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_IMG"),	# 0x9134
    #("",	X,	1,	"GL_MAX_SAMPLES_IMG"),	# 0x9135
    #("",	X,	1,	"GL_TEXTURE_SAMPLES_IMG"),	# 0x9136
    ("glGet",	I,	1,	"GL_MAX_DEBUG_MESSAGE_LENGTH"),	# 0x9143
    ("glGet",	I,	1,	"GL_MAX_DEBUG_LOGGED_MESSAGES"),	# 0x9144
    ("glGet",	I,	1,	"GL_DEBUG_LOGGED_MESSAGES"),	# 0x9145
    ("glGetTexLevelParameter",	I,	1,	"GL_TEXTURE_BUFFER_OFFSET_EXT"),	# 0x919D
    ("glGetTexLevelParameter",	I,	1,	"GL_TEXTURE_BUFFER_SIZE_EXT"),	# 0x919E
    ("glGet",	I,	1,	"GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT_EXT"),	# 0x919F
    #("",	X,	1,	"GL_SHADER_BINARY_DMP"),	# 0x9250
    ("glGet",	B,	1,	"GL_BLEND_ADVANCED_COHERENT_KHR"), # 0x9285
    ("",	X,	1,	"GL_MULTIPLY_KHR"),	# 0x9294
    ("",	X,	1,	"GL_SCREEN_KHR"),	# 0x9295
    ("",	X,	1,	"GL_OVERLAY_KHR"),	# 0x9296
    ("",	X,	1,	"GL_DARKEN_KHR"),	# 0x9297
    ("",	X,	1,	"GL_LIGHTEN_KHR"),	# 0x9298
    ("",	X,	1,	"GL_COLORDODGE_KHR"),	# 0x9299
    ("",	X,	1,	"GL_COLORBURN_KHR"),	# 0x929A
    ("",	X,	1,	"GL_HARDLIGHT_KHR"),	# 0x929B
    ("",	X,	1,	"GL_SOFTLIGHT_KHR"),	# 0x929C
    ("",	X,	1,	"GL_DIFFERENCE_KHR"),	# 0x929E
    ("",	X,	1,	"GL_MINUS_NV"),	# 0x929F
    ("",	X,	1,	"GL_EXCLUSION_KHR"),	# 0x92A0
    ("",	X,	1,	"GL_CONTRAST_NV"),	# 0x92A1
    ("",	X,	1,	"GL_INVERT_RGB_NV"),	# 0x92A3
    ("",	X,	1,	"GL_LINEARDODGE_NV"),	# 0x92A4
    ("",	X,	1,	"GL_LINEARBURN_NV"),	# 0x92A5
    ("",	X,	1,	"GL_VIVIDLIGHT_NV"),	# 0x92A6
    ("",	X,	1,	"GL_LINEARLIGHT_NV"),	# 0x92A7
    ("",	X,	1,	"GL_PINLIGHT_NV"),	# 0x92A8
    ("",	X,	1,	"GL_HARDMIX_NV"),	# 0x92A9
    ("",	X,	1,	"GL_HSL_HUE_KHR"),	# 0x92AD
    ("",	X,	1,	"GL_HSL_SATURATION_KHR"),	# 0x92AE
    ("",	X,	1,	"GL_HSL_COLOR_KHR"),	# 0x92AF
    ("",	X,	1,	"GL_HSL_LUMINOSITY_KHR"),	# 0x92B0
    ("glGet",	F,	8,	"GL_PRIMITIVE_BOUNDING_BOX_EXT"),	# 0x92BE
    ("glGet",	B,	1,	"GL_DEBUG_OUTPUT"),	# 0x92E0
    ("glGetProgramResource",	I,	1,	"GL_IS_PER_PATCH_EXT"),	# 0x92E7
    ("glGetProgramResource",	I,	1,	"GL_REFERENCED_BY_TESS_CONTROL_SHADER_EXT"),	# 0x9307
    ("glGetProgramResource",	I,	1,	"GL_REFERENCED_BY_TESS_EVALUATION_SHADER_EXT"),	# 0x9308
    ("glGetProgramResource",	I,	1,	"GL_REFERENCED_BY_GEOMETRY_SHADER_EXT"),	# 0x9309
    ("glGetFramebufferParameter",	I,	1,	"GL_FRAMEBUFFER_DEFAULT_LAYERS_EXT"),	# 0x9312
    ("glGet",	I,	1,	"GL_MAX_FRAMEBUFFER_LAYERS_EXT"),	# 0x9317
    ("",	X,	1,	"GL_NUM_SAMPLE_COUNTS"),	# 0x9380
    ("glGetFramebufferAttachmentParameter",	I,	1,	"GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_NUM_VIEWS_OVR"),	# 0x9630
    ("glGet",	I,	1,	"GL_MAX_VIEWS_OVR"),	# 0x9631
    ("glGetFramebufferAttachmentParameter",	I,	1,	"GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_BASE_VIEW_INDEX_OVR"),	# 0x9632
#   TBD - missing in Khronos headers - bug?
#    ("glCheckFramebufferStatus",	E,	1,	"GL_FRAMEBUFFER_INCOMPLETE_VIEW_TARGETS_OVR"),	# 0x9633
    ("", I, 1, "GL_STENCIL_BACK_REF"), #0x8CA3
    ("", I, 1, "GL_STENCIL_BACK_VALUE_MASK"), #0x8CA4
    ("", I, 1, "GL_STENCIL_BACK_WRITEMASK"), #0x8CA5
    ("", I, 1, "GL_FRAMEBUFFER_BINDING"), #0x8CA6
    ("glGet", I, 1, "GL_MAX_ELEMENT_INDEX"), #0x8D6B

    # GL ES 3.1 specific defines
    ("glGetTexLevelParameter",	I,	1,	"GL_TEXTURE_WIDTH"),	# 0x1000
    ("glGetTexLevelParameter",	I,	1,	"GL_TEXTURE_HEIGHT"),	# 0x1001
    ("glGetTexLevelParameter",	E,	1,	"GL_TEXTURE_INTERNAL_FORMAT"),	# 0x1003
    ("",	X,	1,	"GL_STENCIL_INDEX"),	# 0x1901
    ("glGetTexLevelParameter",	I,	1,	"GL_TEXTURE_RED_SIZE"),	# 0x805C
    ("glGetTexLevelParameter",	I,	1,	"GL_TEXTURE_GREEN_SIZE"),	# 0x805D
    ("glGetTexLevelParameter",	I,	1,	"GL_TEXTURE_BLUE_SIZE"),	# 0x805E
    ("glGetTexLevelParameter",	I,	1,	"GL_TEXTURE_ALPHA_SIZE"),	# 0x805F
    ("glGetTexLevelParameter",	I,	1,	"GL_TEXTURE_DEPTH"),	# 0x8071
    ("glGetProgram",	B,	1,	"GL_PROGRAM_SEPARABLE"),	# 0x8258
    ("glGet",	I,	1,	"GL_ACTIVE_PROGRAM"),	# 0x8259
    ("glGet",	I,	1,	"GL_PROGRAM_PIPELINE_BINDING"),	# 0x825A
    ("glGet",	I,	1,	"GL_MAX_VIEWPORTS_OES"),	# 0x825B
    ("glGet",	I,	1,	"GL_VIEWPORT_SUBPIXEL_BITS_OES"),	# 0x825C
    ("glGet",	F,	2,	"GL_VIEWPORT_BOUNDS_RANGE_OES"),	# 0x825D
    ("glGet",	E,	1,	"GL_VIEWPORT_INDEX_PROVOKING_VERTEX_OES"),	# 0x825F
    ("glGet",	I,	1,	"GL_MAX_COMPUTE_SHARED_MEMORY_SIZE"),	# 0x8262
    ("glGet",	I,	1,	"GL_MAX_COMPUTE_UNIFORM_COMPONENTS"),	# 0x8263
    ("glGet",	I,	1,	"GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS"),	# 0x8264
    ("glGet",	I,	1,	"GL_MAX_COMPUTE_ATOMIC_COUNTERS"),	# 0x8265
    ("glGet",	I,	1,	"GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS"),	# 0x8266
    ("glGetProgram",	I,	3,	"GL_COMPUTE_WORK_GROUP_SIZE"),	# 0x8267
    ("glGet",	I,	1,	"GL_MAX_UNIFORM_LOCATIONS"),	# 0x826E
    ("glGetVertexAttrib",	I,	1,	"GL_VERTEX_ATTRIB_BINDING"),	# 0x82D4
    ("glGetVertexAttrib",	I,	1,	"GL_VERTEX_ATTRIB_RELATIVE_OFFSET"),	# 0x82D5
    ("",	I,	1,	"GL_VERTEX_BINDING_DIVISOR"),	# 0x82D6
    ("",	I,	1,	"GL_VERTEX_BINDING_OFFSET"),	# 0x82D7
    ("",	I,	1,	"GL_VERTEX_BINDING_STRIDE"),	# 0x82D8
    ("glGet",	I,	1,	"GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET"),	# 0x82D9
    ("glGet",	I,	1,	"GL_MAX_VERTEX_ATTRIB_BINDINGS"),	# 0x82DA
    ("",	X,	1,	"GL_MAX_VERTEX_ATTRIB_STRIDE"),	# 0x82E5
    ("",	X,	1,	"GL_COMPUTE_SHADER_INVOCATIONS_ARB"),	# 0x82F5
    ("",	X,	1,	"GL_OFFSET_TEXTURE_RECTANGLE_NV"),	# 0x864C
    ("",	X,	1,	"GL_OFFSET_TEXTURE_RECTANGLE_SCALE_NV"),	# 0x864D
    ("glGetTexLevelParameter",	B,	1,	"GL_TEXTURE_COMPRESSED"),	# 0x86A1
    ("",	X,	1,	"GL_OFFSET_TEXTURE_2D_NV"),	# 0x86E8
    ("glGetTexLevelParameter",	I,	1,	"GL_TEXTURE_DEPTH_SIZE"),	# 0x884A
    ("",	X,	1,	"GL_OFFSET_PROJECTIVE_TEXTURE_2D_NV"),	# 0x8850
    ("",	X,	1,	"GL_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE_NV"),	# 0x8851
    ("",	X,	1,	"GL_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_NV"),	# 0x8852
    ("",	X,	1,	"GL_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE_NV"),	# 0x8853
    ("",	X,	1,	"GL_OFFSET_HILO_TEXTURE_2D_NV"),	# 0x8854
    ("",	X,	1,	"GL_OFFSET_HILO_TEXTURE_RECTANGLE_NV"),	# 0x8855
    ("",	X,	1,	"GL_OFFSET_HILO_PROJECTIVE_TEXTURE_2D_NV"),	# 0x8856
    ("",	X,	1,	"GL_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE_NV"),	# 0x8857
    ("glGetProgramiv",	I,	1,	"GL_GEOMETRY_SHADER_INVOCATIONS_EXT"),	# 0x887F
    ("",	X,	1,	"GL_READ_ONLY"),	# 0x88B8
    ("",	X,	1,	"GL_WRITE_ONLY"),	# 0x88B9
    ("",	X,	1,	"GL_READ_WRITE"),	# 0x88BA
    ("glGetTexLevelParameter",	I,	1,	"GL_TEXTURE_STENCIL_SIZE"),	# 0x88F1
    ("",	X,	1,	"GL_UNIFORM_BUFFER"),	# 0x8A11
    #("",	X,	1,	"GL_TEXTURE_WIDTH_QCOM"),	# 0x8BD2
    #("",	X,	1,	"GL_TEXTURE_HEIGHT_QCOM"),	# 0x8BD3
    #("",	X,	1,	"GL_TEXTURE_DEPTH_QCOM"),	# 0x8BD4
    #("",	X,	1,	"GL_TEXTURE_INTERNAL_FORMAT_QCOM"),	# 0x8BD5
    ("glGetTexLevelParameter",	E,	1,	"GL_TEXTURE_RED_TYPE"),	# 0x8C10
    ("glGetTexLevelParameter",	E,	1,	"GL_TEXTURE_GREEN_TYPE"),	# 0x8C11
    ("glGetTexLevelParameter",	E,	1,	"GL_TEXTURE_BLUE_TYPE"),	# 0x8C12
    ("glGetTexLevelParameter",	E,	1,	"GL_TEXTURE_ALPHA_TYPE"),	# 0x8C13
    ("glGetTexLevelParameter",	E,	1,	"GL_TEXTURE_DEPTH_TYPE"),	# 0x8C16
    ("",	X,	1,	"GL_TEXTURE_SHARED_SIZE"),	# 0x8C3F
    ("",	X,	1,	"GL_STENCIL_INDEX1"),	# 0x8D46
    ("",	X,	1,	"GL_STENCIL_INDEX4"),	# 0x8D47
    ("",	X,	1,	"GL_STENCIL_INDEX8"),	# 0x8D48
    ("",	X,	1,	"GL_STENCIL_INDEX16"),	# 0x8D49
    ("glGet",	I,	1,	"GL_MAX_GEOMETRY_OUTPUT_VERTICES_EXT"),	# 0x8DE0
    ("glGet",	I,	1,	"GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT"),	# 0x8DE1
    ("",	X,	1,	"GL_UNIFORM_BUFFER_EXT"),	# 0x8DEE
    ("glGetMultisample",	I,	1,	"GL_SAMPLE_POSITION"),	# 0x8E50
    ("glGet",	B,	1,	"GL_SAMPLE_MASK"),	# 0x8E51
    ("glGet",	I,	1,	"GL_SAMPLE_MASK_VALUE"),	# 0x8E52
    ("glGet",	I,	1,	"GL_MAX_SAMPLE_MASK_WORDS"),	# 0x8E59
    ("glGet",	X,	1,	"GL_MAX_GEOMETRY_SHADER_INVOCATIONS_EXT"),	# 0x8E5A
    ("",	X,	1,	"GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET"),	# 0x8E5E
    ("",	X,	1,	"GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET"),	# 0x8E5F
    ("glGet",	I,	1,	"GL_MAX_IMAGE_UNITS"),	# 0x8F38
    ("",	X,	1,	"GL_IMAGE_BINDING_NAME"),	# 0x8F3A
    ("",	X,	1,	"GL_IMAGE_BINDING_LEVEL"),	# 0x8F3B
    ("",	X,	1,	"GL_IMAGE_BINDING_LAYERED"),	# 0x8F3C
    ("",	X,	1,	"GL_IMAGE_BINDING_LAYER"),	# 0x8F3D
    ("",	X,	1,	"GL_IMAGE_BINDING_ACCESS"),	# 0x8F3E
    ("",	X,	1,	"GL_DRAW_INDIRECT_BUFFER"),	# 0x8F3F
    ("glGet",	I,	1,	"GL_DRAW_INDIRECT_BUFFER_BINDING"),	# 0x8F43
    ("",	X,	1,	"GL_VERTEX_BINDING_BUFFER"),	# 0x8F4F
    ("",	X,	1,	"GL_IMAGE_2D"),	# 0x904D
    ("",	X,	1,	"GL_IMAGE_3D"),	# 0x904E
    ("",	X,	1,	"GL_IMAGE_2D_RECT"),	# 0x904F
    ("",	X,	1,	"GL_IMAGE_CUBE"),	# 0x9050
    ("",	X,	1,	"GL_IMAGE_2D_ARRAY"),	# 0x9053
    ("",	X,	1,	"GL_IMAGE_CUBE_MAP_ARRAY"),	# 0x9054
    ("",	X,	1,	"GL_IMAGE_2D_MULTISAMPLE"),	# 0x9055
    ("",	X,	1,	"GL_IMAGE_2D_MULTISAMPLE_ARRAY"),	# 0x9056
    ("",	X,	1,	"GL_INT_IMAGE_2D"),	# 0x9058
    ("",	X,	1,	"GL_INT_IMAGE_3D"),	# 0x9059
    ("",	X,	1,	"GL_INT_IMAGE_2D_RECT"),	# 0x905A
    ("",	X,	1,	"GL_INT_IMAGE_CUBE"),	# 0x905B
    ("",	X,	1,	"GL_INT_IMAGE_2D_ARRAY"),	# 0x905E
    ("",	X,	1,	"GL_INT_IMAGE_CUBE_MAP_ARRAY"),	# 0x905F
    ("",	X,	1,	"GL_INT_IMAGE_2D_MULTISAMPLE"),	# 0x9060
    ("",	X,	1,	"GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY"),	# 0x9061
    ("",	X,	1,	"GL_UNSIGNED_INT_IMAGE_2D"),	# 0x9063
    ("",	X,	1,	"GL_UNSIGNED_INT_IMAGE_3D"),	# 0x9064
    ("",	X,	1,	"GL_UNSIGNED_INT_IMAGE_2D_RECT"),	# 0x9065
    ("",	X,	1,	"GL_UNSIGNED_INT_IMAGE_CUBE"),	# 0x9066
    ("",	X,	1,	"GL_UNSIGNED_INT_IMAGE_2D_ARRAY"),	# 0x9069
    ("",	X,	1,	"GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY"),	# 0x906A
    ("",	X,	1,	"GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE"),	# 0x906B
    ("",	X,	1,	"GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY"),	# 0x906C
    ("",	X,	1,	"GL_IMAGE_BINDING_FORMAT"),	# 0x906E
    ("",	X,	1,	"GL_IMAGE_FORMAT_COMPATIBILITY_TYPE"),	# 0x90C7
    ("",	X,	1,	"GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE"),	# 0x90C8
    ("",	X,	1,	"GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS"),	# 0x90C9
    ("glGet",	I,	1,	"GL_MAX_VERTEX_IMAGE_UNIFORMS"),	# 0x90CA
    ("glGet",	I,	1,	"GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS_EXT"),	# 0x90CB
    ("glGet",	I,	1,	"GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS_EXT"),	# 0x90CC
    ("glGet",	I,	1,	"GL_MAX_GEOMETRY_IMAGE_UNIFORMS_EXT"),	# 0x90CD
    ("glGet",	I,	1,	"GL_MAX_FRAGMENT_IMAGE_UNIFORMS"),	# 0x90CE
    ("glGet",	I,	1,	"GL_MAX_COMBINED_IMAGE_UNIFORMS"),	# 0x90CF
    ("",	I,	1,	"GL_SHADER_STORAGE_BUFFER"),	# 0x90D2
    ("",	I,	1,	"GL_SHADER_STORAGE_BUFFER_BINDING"),	# 0x90D3
    ("",	I,	1,	"GL_SHADER_STORAGE_BUFFER_START"),	# 0x90D4
    ("",	I,	1,	"GL_SHADER_STORAGE_BUFFER_SIZE"),	# 0x90D5
    ("",	I,	1,	"GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS"),	# 0x90D6
    ("glGet",	I,	1,	"GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS_EXT"),	# 0x90D7
    ("glGet",	I,	1,	"GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS_EXT"),	# 0x90D8
    ("glGet",	I,	1,	"GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS_EXT"),	# 0x90D9
    ("",	I,	1,	"GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS"),	# 0x90DA
    ("glGet",	I,	1,	"GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS"),	# 0x90DB
    ("",	I,	1,	"GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS"),	# 0x90DC
    ("",	I,	1,	"GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS"),	# 0x90DD
    ("",	I,	1,	"GL_MAX_SHADER_STORAGE_BLOCK_SIZE"),	# 0x90DE
    ("",	X,	1,	"GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT"),	# 0x90DF
    ("glGetTexParameter",	E,	1,	"GL_DEPTH_STENCIL_TEXTURE_MODE"),	# 0x90EA
    ("glGet",	I,	1,	"GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS"),	# 0x90EB
    ("",	X,	1,	"GL_UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER"),	# 0x90EC
    ("",	X,	1,	"GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_COMPUTE_SHADER"),	# 0x90ED
    ("",	X,	1,	"GL_DISPATCH_INDIRECT_BUFFER"),	# 0x90EE
    ("glGet",	I,	1,	"GL_DISPATCH_INDIRECT_BUFFER_BINDING"),	# 0x90EF
    ("",	X,	1,	"GL_TEXTURE_2D_MULTISAMPLE"),	# 0x9100
    ("",	X,	1,	"GL_TEXTURE_2D_MULTISAMPLE_ARRAY"),	# 0x9102
    ("glGet",	I,	1,	"GL_TEXTURE_BINDING_2D_MULTISAMPLE"),	# 0x9104
    ("glGet",	I,	1,	"GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY_OES"),	# 0x9105
    ("glGetTexLevelParameter",	I,	1,	"GL_TEXTURE_SAMPLES"),	# 0x9106
    ("glGetTexLevelParameter",	B,	1,	"GL_TEXTURE_FIXED_SAMPLE_LOCATIONS"),	# 0x9107
    ("",	X,	1,	"GL_SAMPLER_2D_MULTISAMPLE"),	# 0x9108
    ("",	X,	1,	"GL_INT_SAMPLER_2D_MULTISAMPLE"),	# 0x9109
    ("",	X,	1,	"GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE"),	# 0x910A
    ("",	X,	1,	"GL_SAMPLER_2D_MULTISAMPLE_ARRAY"),	# 0x910B
    ("",	X,	1,	"GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY"),	# 0x910C
    ("",	X,	1,	"GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY"),	# 0x910D
    ("glGet",	I,	1,	"GL_MAX_COLOR_TEXTURE_SAMPLES"),	# 0x910E
    ("glGet",	I,	1,	"GL_MAX_DEPTH_TEXTURE_SAMPLES"),	# 0x910F
    ("glGet",	I,	1,	"GL_MAX_INTEGER_SAMPLES"),	# 0x9110
    ("",	I,	1,	"GL_TEXTURE_SAMPLES_IMG"),	# 0x9136
    ("glGetProgramPipeline",	I,	1,	"GL_COMPUTE_SHADER"),	# 0x91B9
    ("glGet",	I,	1,	"GL_MAX_COMPUTE_UNIFORM_BLOCKS"),	# 0x91BB
    ("glGet",	I,	1,	"GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS"),	# 0x91BC
    ("glGet",	I,	1,	"GL_MAX_COMPUTE_IMAGE_UNIFORMS"),	# 0x91BD
    ("glGet",	I,	1,	"GL_MAX_COMPUTE_WORK_GROUP_COUNT"),	# 0x91BE
    ("glGet",	I,	1,	"GL_MAX_COMPUTE_WORK_GROUP_SIZE"),	# 0x91BF
    ("",	X,	1,	"GL_ATOMIC_COUNTER_BUFFER"),	# 0x92C0
    ("",	X,	1,	"GL_ATOMIC_COUNTER_BUFFER_BINDING"),	# 0x92C1
    ("",	X,	1,	"GL_ATOMIC_COUNTER_BUFFER_START"),	# 0x92C2
    ("",	X,	1,	"GL_ATOMIC_COUNTER_BUFFER_SIZE"),	# 0x92C3
    ("",	X,	1,	"GL_ATOMIC_COUNTER_BUFFER_DATA_SIZE"),	# 0x92C4
    ("",	X,	1,	"GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS"),	# 0x92C5
    ("",	X,	1,	"GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTER_INDICES"),	# 0x92C6
    ("",	X,	1,	"GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_VERTEX_SHADER"),	# 0x92C7
    ("",	X,	1,	"GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_CONTROL_SHADER"),	# 0x92C8
    ("",	X,	1,	"GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_EVALUATION_SHADER"),	# 0x92C9
    ("",	X,	1,	"GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_GEOMETRY_SHADER"),	# 0x92CA
    ("",	X,	1,	"GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_FRAGMENT_SHADER"),	# 0x92CB
    ("glGet",	I,	1,	"GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS"),	# 0x92CC
    ("glGet",	I,	1,	"GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS_EXT"),	# 0x92CD
    ("glGet",	I,	1,	"GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS_EXT"),	# 0x92CE
    ("glGet",	I,	1,	"GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS_EXT"),	# 0x92CF
    ("glGet",	I,	1,	"GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS"),	# 0x92D0
    ("glGet",	I,	1,	"GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS"),	# 0x92D1
    ("glGet",	I,	1,	"GL_MAX_VERTEX_ATOMIC_COUNTERS"),	# 0x92D2
    ("glGet",	I,	1,	"GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS_EXT"),	# 0x92D3
    ("glGet",	I,	1,	"GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS_EXT"),	# 0x92D4
    ("glGet",	I,	1,	"GL_MAX_GEOMETRY_ATOMIC_COUNTERS_EXT"),	# 0x92D5
    ("glGet",	I,	1,	"GL_MAX_FRAGMENT_ATOMIC_COUNTERS"),	# 0x92D6
    ("glGet",	I,	1,	"GL_MAX_COMBINED_ATOMIC_COUNTERS"),	# 0x92D7
    ("glGet",	I,	1,	"GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE"),	# 0x92D8
    ("glGet",	I,	1,	"GL_ACTIVE_ATOMIC_COUNTER_BUFFERS"),	# 0x92D9
    ("glGet",	I,	1,	"GL_UNIFORM_ATOMIC_COUNTER_BUFFER_INDEX"),	# 0x92DA
    ("glGet",	I,	1,	"GL_UNSIGNED_INT_ATOMIC_COUNTER"),	# 0x92DB
    ("glGet",	I,	1,	"GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS"),	# 0x92DC
    ("",	X,	1,	"GL_UNIFORM"),	# 0x92E1
    ("",	X,	1,	"GL_UNIFORM_BLOCK"),	# 0x92E2
    ("",	X,	1,	"GL_PROGRAM_INPUT"),	# 0x92E3
    ("",	X,	1,	"GL_PROGRAM_OUTPUT"),	# 0x92E4
    ("",	X,	1,	"GL_BUFFER_VARIABLE"),	# 0x92E5
    ("",	X,	1,	"GL_SHADER_STORAGE_BLOCK"),	# 0x92E6
    ("",	X,	1,	"GL_TRANSFORM_FEEDBACK_VARYING"),	# 0x92F4
    ("",	I,	1,	"GL_ACTIVE_RESOURCES"),	# 0x92F5
    ("",	I,	1,	"GL_MAX_NAME_LENGTH"),	# 0x92F6
    ("",	I,	1,	"GL_MAX_NUM_ACTIVE_VARIABLES"),	# 0x92F7
    ("",	I,	1,	"GL_NAME_LENGTH"),	# 0x92F9
    ("",	I,	1,	"GL_TYPE"),	# 0x92FA
    ("",	I,	1,	"GL_ARRAY_SIZE"),	# 0x92FB
    ("",	I,	1,	"GL_OFFSET"),	# 0x92FC
    ("",	I,	1,	"GL_BLOCK_INDEX"),	# 0x92FD
    ("",	I,	1,	"GL_ARRAY_STRIDE"),	# 0x92FE
    ("",	I,	1,	"GL_MATRIX_STRIDE"),	# 0x92FF
    ("",	I,	1,	"GL_IS_ROW_MAJOR"),	# 0x9300
    ("",	I,	1,	"GL_ATOMIC_COUNTER_BUFFER_INDEX"),	# 0x9301
    ("",	I,	1,	"GL_BUFFER_BINDING"),	# 0x9302
    ("",	I,	1,	"GL_BUFFER_DATA_SIZE"),	# 0x9303
    ("",	I,	1,	"GL_NUM_ACTIVE_VARIABLES"),	# 0x9304
    ("",	I,	1,	"GL_ACTIVE_VARIABLES"),	# 0x9305
    ("",	I,	1,	"GL_REFERENCED_BY_VERTEX_SHADER"),	# 0x9306
    ("",	I,	1,	"GL_REFERENCED_BY_FRAGMENT_SHADER"),	# 0x930A
    ("",	I,	1,	"GL_REFERENCED_BY_COMPUTE_SHADER"),	# 0x930B
    ("",	I,	1,	"GL_TOP_LEVEL_ARRAY_SIZE"),	# 0x930C
    ("",	I,	1,	"GL_TOP_LEVEL_ARRAY_STRIDE"),	# 0x930D
    ("",	I,	1,	"GL_LOCATION"),	# 0x930E
    ("",	I,	1,	"GL_FRAMEBUFFER_DEFAULT_WIDTH"),	# 0x9310
    ("",	I,	1,	"GL_FRAMEBUFFER_DEFAULT_HEIGHT"),	# 0x9311
    ("",	I,	1,	"GL_FRAMEBUFFER_DEFAULT_SAMPLES"),	# 0x9313
    ("",	B,	1,	"GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS"),	# 0x9314
    ("glGet",	I,	1,	"GL_MAX_FRAMEBUFFER_WIDTH"),	# 0x9315
    ("glGet",	I,	1,	"GL_MAX_FRAMEBUFFER_HEIGHT"),	# 0x9316
    ("glGet",	I,	1,	"GL_MAX_FRAMEBUFFER_SAMPLES"),	# 0x9318
    ("",	X,	1,	"GL_LOCATION_COMPONENT"),		# 0x934A
]
