# set IOS_SVN_REV to svn revision number
echo -e "// THIS FILE IS AUTOMATICALLY GENERATED BY gen_version_info.sh\\n#define IOS_REV \"r3p0 official\"" > ../../../project/iOS/retracer_application/retracer_application/ios_rev.h
