SET(CMAKE_SYSTEM_NAME Linux)
SET(WINDOWSYSTEM fbdev)
SET(ARCH x64)

SET(ENABLE_TOOLS TRUE)
SET(ENABLE_PYTHON_TOOLS FALSE)

set(CC_CFLAGS "-m64")
set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++")
